namespace AP.ChevronCoop.Entities.Loans.LoanApplications;

public class LoanApplicationMasterView
{
    public long? RowNumber { get; set; }
    public string Id { get; set; }
    public string ApplicationNo { get; set; }
    public string? AccountNo { get; set; }
    public string LoanProductId { get; set; }
    public string? ApprovalId { get; set; }
    public string CustomerId { get; set; }
    public decimal Principal { get; set; }
    public string TenureUnit { get; set; }
    public decimal TenureValue { get; set; }
    public DateTimeOffset RepaymentCommencementDate { get; set; }
    public bool UseSpecialDeposit { get; set; }
    public string? SpecialDepositId { get; set; }
    public string? CustomerDisbursementAccountId { get; set; }
    public string? QualificationTargetProductId { get; set; }
    public string Status { get; set; }
    public string QualificationTargetProductType { get; set; }
    public string? Description { get; set; }
    public bool IsActive { get; set; }
    public string? CreatedByUserId { get; set; }
    public DateTimeOffset? DateCreated { get; set; }
    public string? UpdatedByUserId { get; set; }
    public DateTimeOffset? DateUpdated { get; set; }
    public string? DeletedByUserId { get; set; }
    public bool IsDeleted { get; set; }
    public DateTimeOffset? DateDeleted { get; set; }
    public Guid RowVersion { get; set; }
    public string? FullText { get; set; }
    public string? Tags { get; set; }
    public string? Caption { get; set; }
    public string? LoanProductId_Code { get; set; }
    public string? LoanProductId_PayrollCode { get; set; }
    public string? LoanProductId_Name { get; set; }
    public string? LoanProductId_ShortName { get; set; }
    public string? LoanProductId_ApprovalWorkflowId { get; set; }
    public string? LoanProductId_ApprovalId { get; set; }
    public decimal? LoanProductId_PrincipalMultiple { get; set; }
    public decimal? LoanProductId_PrincipalMinLimit { get; set; }
    public decimal? LoanProductId_PrincipalMaxLimit { get; set; }
    public string? LoanProductId_TenureUnit { get; set; }
    public decimal? LoanProductId_MinTenureValue { get; set; }
    public decimal? LoanProductId_MaxTenureValue { get; set; }
    public string? LoanProductId_RepaymentPeriod { get; set; }
    public string? LoanProductId_InterestMethod { get; set; }
    public string? LoanProductId_InterestCalculationMethod { get; set; }
    public decimal? LoanProductId_DaysInYear { get; set; }
    public decimal? LoanProductId_InterestRate { get; set; }
    public bool? LoanProductId_HasAdminCharges { get; set; }
    public bool? LoanProductId_IsTargetLoan { get; set; }
    public string? LoanProductId_BenefitCode { get; set; }
    public string? LoanProductId_AllowedOffsetType { get; set; }
    public string? LoanProductId_OffsetPeriodUnit { get; set; }
    public decimal? LoanProductId_OffsetPeriodValue { get; set; }
    public bool? LoanProductId_EnableSavingsOffset { get; set; }
    public bool? LoanProductId_EnableChargeWaiver { get; set; }
    public bool? LoanProductId_EnableTopUp { get; set; }
    public bool? LoanProductId_EnableTopUpCharges { get; set; }
    public bool? LoanProductId_EnableAdminOffsetCharge { get; set; }
    public bool? LoanProductId_EnableWaitingPeriod { get; set; }
    public string? LoanProductId_WaitingPeriodUnit { get; set; }
    public decimal? LoanProductId_WaitingPeriodValue { get; set; }
    public bool? LoanProductId_EnableWaitingPeriodCharge { get; set; }
    public bool? LoanProductId_IsGuarantorRequired { get; set; }
    public int? LoanProductId_GuarantorMinYear { get; set; }
    public decimal? LoanProductId_GuarantorAmountLimit { get; set; }
    public int? LoanProductId_EmployeeGuarantorCount { get; set; }
    public int? LoanProductId_NonEmployeeGuarantorCount { get; set; }
    public string? LoanProductId_QualificationTargetProduct { get; set; }
    public decimal? LoanProductId_QualificationMinBalancePercentage { get; set; }
    public string? LoanProductId_SavingsOffSetProductIdList { get; set; }
    public string? LoanProductId_MemberTypeIdList { get; set; }
    public int? LoanProductId_MinimumAge { get; set; }
    public int? LoanProductId_MaximumAge { get; set; }
    public string? LoanProductId_DefaultCurrencyId { get; set; }
    public string? LoanProductId_LoanProductType { get; set; }
    public string? LoanProductId_BankDepositAccountId { get; set; }
    public string? LoanProductId_DisbursementAccountId { get; set; }
    public string? LoanProductId_PrincipalAccountId { get; set; }
    public string? LoanProductId_PrincipalLossAccountId { get; set; }
    public string? LoanProductId_InterestIncomeAccountId { get; set; }
    public string? LoanProductId_UnearnedInterestAccountId { get; set; }
    public string? LoanProductId_InterestLossAccountId { get; set; }
    public string? LoanProductId_PenalInterestReceivableAccountId { get; set; }
    public string? LoanProductId_InterestWaivedAccountId { get; set; }
    public string? LoanProductId_ChargesIncomeAccountId { get; set; }
    public string? LoanProductId_ChargesAccrualAccountId { get; set; }
    public string? LoanProductId_ChargesWaivedAccountId { get; set; }
    public string? LoanProductId_Status { get; set; }
    public int? LoanProductId_PublicationType { get; set; }
    public string? LoanProductId_PublishedByUserId { get; set; }
    public bool? LoanProductId_IsActive { get; set; }
    public string? LoanProductId_CreatedByUserId { get; set; }
    public string? LoanProductId_UpdatedByUserId { get; set; }
    public string? LoanProductId_DeletedByUserId { get; set; }
    public bool? LoanProductId_IsDeleted { get; set; }
    public string? LoanProductId_Tags { get; set; }
    public string? LoanProductId_Caption { get; set; }
    public string? ApprovalId_Module { get; set; }
    public string? ApprovalId_ApprovalType { get; set; }
    public string? ApprovalId_Status { get; set; }
    public int? ApprovalId_CurrentSequence { get; set; }
    public string? ApprovalId_ApprovalWorkflowId { get; set; }
    public string? ApprovalId_Payload { get; set; }
    public bool? ApprovalId_IsApprovalCompleted { get; set; }
    public string? ApprovalId_Comment { get; set; }
    public string? ApprovalId_EntityId { get; set; }
    public int? ApprovalId_TriedCount { get; set; }
    public bool? ApprovalId_IsActive { get; set; }
    public string? ApprovalId_CreatedByUserId { get; set; }
    public string? ApprovalId_UpdatedByUserId { get; set; }
    public string? ApprovalId_DeletedByUserId { get; set; }
    public bool? ApprovalId_IsDeleted { get; set; }
    public string? ApprovalId_Tags { get; set; }
    public string? ApprovalId_Caption { get; set; }
    public string? ApprovalId_ApprovalViewModelPayload { get; set; }
    public string? CustomerId_CustomerNo { get; set; }
    public string? CustomerId_ApplicationUserId { get; set; }
    public string? CustomerId_CashAccountId { get; set; }
    public int? CustomerId_YearsOfService { get; set; }
    public bool? CustomerId_IsKycStarted { get; set; }
    public bool? CustomerId_IsKycCompleted { get; set; }
    public DateTime? CustomerId_KycStartDate { get; set; }
    public DateTime? CustomerId_KycCompletedDate { get; set; }
    public string? CustomerId_Status { get; set; }
    public string? CustomerId_MemberType { get; set; }
    public string? CustomerId_Gender { get; set; }
    public string? CustomerId_ProfileImageUrl { get; set; }
    public string? CustomerId_PassportUrl { get; set; }
    public string? CustomerId_IdentificationType { get; set; }
    public string? CustomerId_IdentificationNumber { get; set; }
    public string? CustomerId_IdentificationUrl { get; set; }
    public bool? CustomerId_KycSubmitted { get; set; }
    public DateTime? CustomerId_KycSubmittedOn { get; set; }
    public bool? CustomerId_KycApproved { get; set; }
    public DateTime? CustomerId_KycApprovedOn { get; set; }
    public bool? CustomerId_KycApprovedBy { get; set; }
    public string? CustomerId_FirstName { get; set; }
    public string? CustomerId_LastName { get; set; }
    public string? CustomerId_MiddleName { get; set; }
    public string? CustomerId_DepartmentId { get; set; }
    public string? CustomerId_MemberId { get; set; }
    public string? CustomerId_CAI { get; set; }
    public string? CustomerId_RetireeNumber { get; set; }
    public string? CustomerId_StateOfOrigin { get; set; }
    public string? CustomerId_PrimaryEmail { get; set; }
    public string? CustomerId_SecondaryEmail { get; set; }
    public string? CustomerId_PrimaryPhone { get; set; }
    public string? CustomerId_SecondaryPhone { get; set; }
    public string? CustomerId_ResidentialAddress { get; set; }
    public string? CustomerId_OfficeAddress { get; set; }
    public string? CustomerId_Rank { get; set; }
    public string? CustomerId_JobRole { get; set; }
    public DateTimeOffset? CustomerId_DOB { get; set; }
    public string? CustomerId_Address { get; set; }
    public string? CustomerId_Country { get; set; }
    public string? CustomerId_State { get; set; }
    public bool? CustomerId_IsActive { get; set; }
    public string? CustomerId_CreatedByUserId { get; set; }
    public string? CustomerId_UpdatedByUserId { get; set; }
    public string? CustomerId_DeletedByUserId { get; set; }
    public bool? CustomerId_IsDeleted { get; set; }
    public string? CustomerId_Tags { get; set; }
    public string? CustomerId_Caption { get; set; }
    public DateTime? CustomerId_DateOfEmployment { get; set; }
    public string? SpecialDepositId_ApplicationId { get; set; }
    public string? SpecialDepositId_AccountNo { get; set; }
    public string? SpecialDepositId_CustomerId { get; set; }
    public string? SpecialDepositId_DepositProductId { get; set; }
    public string? SpecialDepositId_DepositAccountId { get; set; }
    public string? SpecialDepositId_ChargesAccruedAccountId { get; set; }
    public string? SpecialDepositId_ChargesIncomeAccountId { get; set; }
    public string? SpecialDepositId_ChargesWaivedAccountId { get; set; }
    public string? SpecialDepositId_InterestEarnedAccountId { get; set; }
    public string? SpecialDepositId_InterestPayoutAccountId { get; set; }
    public decimal? SpecialDepositId_FundingAmount { get; set; }
    public decimal? SpecialDepositId_InterestRate { get; set; }
    public DateTime? SpecialDepositId_LastInterestComputationDate { get; set; }
    public decimal? SpecialDepositId_MaximumBalanceLimit { get; set; }
    public decimal? SpecialDepositId_MinimumBalanceLimit { get; set; }
    public decimal? SpecialDepositId_SingleWithdrawalLimit { get; set; }
    public decimal? SpecialDepositId_DailyWithdrawalLimit { get; set; }
    public decimal? SpecialDepositId_WeeklyWithdrawalLimit { get; set; }
    public decimal? SpecialDepositId_MonthlyWithdrawalLimit { get; set; }
    public bool? SpecialDepositId_IsClosed { get; set; }
    public DateTime? SpecialDepositId_DateClosed { get; set; }
    public string? SpecialDepositId_ClosedByUserId { get; set; }
    public bool? SpecialDepositId_IsActive { get; set; }
    public string? SpecialDepositId_CreatedByUserId { get; set; }
    public string? SpecialDepositId_UpdatedByUserId { get; set; }
    public string? SpecialDepositId_DeletedByUserId { get; set; }
    public bool? SpecialDepositId_IsDeleted { get; set; }
    public string? SpecialDepositId_Tags { get; set; }
    public string? SpecialDepositId_Caption { get; set; }
    public string? CustomerDisbursementAccountId_LedgerAccountId { get; set; }
    public string? CustomerDisbursementAccountId_CustomerId { get; set; }
    public string? CustomerDisbursementAccountId_BankId { get; set; }
    public string? CustomerDisbursementAccountId_AccountName { get; set; }
    public string? CustomerDisbursementAccountId_AccountNumber { get; set; }
    public string? CustomerDisbursementAccountId_BVN { get; set; }
    public string? CustomerDisbursementAccountId_Branch { get; set; }
    public bool? CustomerDisbursementAccountId_IsActive { get; set; }
    public string? CustomerDisbursementAccountId_CreatedByUserId { get; set; }
    public string? CustomerDisbursementAccountId_UpdatedByUserId { get; set; }
    public string? CustomerDisbursementAccountId_DeletedByUserId { get; set; }
    public bool? CustomerDisbursementAccountId_IsDeleted { get; set; }
    public string? CustomerDisbursementAccountId_Tags { get; set; }
    public string? CustomerDisbursementAccountId_Caption { get; set; }
}