namespace AP.ChevronCoop.Entities.Loans.LoanRepayment;

public class LoanRepaymentMasterView
{
  public long? RowNumber { get; set; }
  public string Id { get; set; }
  public string RepaymentMode { get; set; }
  public string LoanAccountId { get; set; }
  public string? LoanRepaymentScheduleId { get; set; }
  public string? PayrollDeductionScheduleItemId { get; set; }
  public string? LoanOffsetId { get; set; }
  public string? ApprovalId { get; set; }
  public decimal Amount { get; set; }
  public decimal Principal { get; set; }
  public decimal Interest { get; set; }
  public DateTimeOffset? PeriodStartDate { get; set; }
  public DateTimeOffset? RepaymentDate { get; set; }
  public string? PaymentAccountId { get; set; }
  public string? CustomerBankAccountId { get; set; }
  public string? TransactionJournalId { get; set; }
  public bool IsProcessed { get; set; }
  public DateTime? ProcessedDate { get; set; }
  public string Status { get; set; }
  public string? Description { get; set; }
  public bool IsActive { get; set; }
  public string? CreatedByUserId { get; set; }
  public DateTimeOffset? DateCreated { get; set; }
  public string? UpdatedByUserId { get; set; }
  public DateTimeOffset? DateUpdated { get; set; }
  public string? DeletedByUserId { get; set; }
  public bool IsDeleted { get; set; }
  public DateTimeOffset? DateDeleted { get; set; }
  public Guid RowVersion { get; set; }
  public string? FullText { get; set; }
  public string? Tags { get; set; }
  public string? Caption { get; set; }
  public string? LoanAccountId_AccountNo { get; set; }
  public string? LoanAccountId_LoanApplicationId { get; set; }
  public string? LoanAccountId_CustomerId { get; set; }
  public string? LoanAccountId_PrincipalBalanceAccountId { get; set; }
  public string? LoanAccountId_PrincipalLossAccountId { get; set; }
  public string? LoanAccountId_EarnedInterestAccountId { get; set; }
  public string? LoanAccountId_InterestBalanceAccountId { get; set; }
  public string? LoanAccountId_UnearnedInterestAccountId { get; set; }
  public string? LoanAccountId_InterestLossAccountId { get; set; }
  public string? LoanAccountId_InterestWaivedAccountId { get; set; }
  public string? LoanAccountId_ChargesAccruedAccountId { get; set; }
  public string? LoanAccountId_ChargesIncomeAccountId { get; set; }
  public string? LoanAccountId_ChargesWaivedAccountId { get; set; }
  public decimal? LoanAccountId_Principal { get; set; }
  public string? LoanAccountId_TenureUnit { get; set; }
  public decimal? LoanAccountId_TenureValue { get; set; }
  public DateTimeOffset? LoanAccountId_RepaymentCommencementDate { get; set; }
  public bool? LoanAccountId_UseSpecialDeposit { get; set; }
  public string? LoanAccountId_SpecialDepositAccountId { get; set; }
  public string? LoanAccountId_DestinationAccountId { get; set; }
  public bool? LoanAccountId_IsClosed { get; set; }
  public DateTime? LoanAccountId_DateClosed { get; set; }
  public string? LoanAccountId_ClosedByUserId { get; set; }
  public string? LoanAccountId_LoanTopupId { get; set; }
  public string? LoanAccountId_InterestPayoutAccountId { get; set; }
  public bool? LoanAccountId_IsActive { get; set; }
  public string? LoanAccountId_CreatedByUserId { get; set; }
  public string? LoanAccountId_UpdatedByUserId { get; set; }
  public string? LoanAccountId_DeletedByUserId { get; set; }
  public bool? LoanAccountId_IsDeleted { get; set; }
  public string? LoanAccountId_Tags { get; set; }
  public string? LoanAccountId_Caption { get; set; }
  public string? LoanAccountId_LoanCreationType { get; set; }
  public string? LoanAccountId_ParentAccountId { get; set; }
  public string? LoanAccountId_RootParentAccountId { get; set; }
  public string? LoanRepaymentScheduleId_LoanAccountId { get; set; }
  public int? LoanRepaymentScheduleId_RepaymentNo { get; set; }
  public string? LoanRepaymentScheduleId_BatchRefNo { get; set; }
  public string? LoanRepaymentScheduleId_TenureUnit { get; set; }
  public decimal? LoanRepaymentScheduleId_TenureValue { get; set; }
  public DateTime? LoanRepaymentScheduleId_PeriodStartDate { get; set; }
  public DateTime? LoanRepaymentScheduleId_DueDate { get; set; }
  public int? LoanRepaymentScheduleId_DaysInPeriod { get; set; }
  public decimal? LoanRepaymentScheduleId_PeriodPayment { get; set; }
  public decimal? LoanRepaymentScheduleId_CumulativeTotal { get; set; }
  public decimal? LoanRepaymentScheduleId_TotalBalance { get; set; }
  public decimal? LoanRepaymentScheduleId_PeriodPrincipal { get; set; }
  public decimal? LoanRepaymentScheduleId_CumulativePrincipal { get; set; }
  public decimal? LoanRepaymentScheduleId_PrincipalBalance { get; set; }
  public decimal? LoanRepaymentScheduleId_PeriodInterest { get; set; }
  public decimal? LoanRepaymentScheduleId_CumulativeInterest { get; set; }
  public decimal? LoanRepaymentScheduleId_InterestBalance { get; set; }
  public bool? LoanRepaymentScheduleId_IsPaid { get; set; }
  public bool? LoanRepaymentScheduleId_IsPrincipalAllocated { get; set; }
  public bool? LoanRepaymentScheduleId_IsInterestAllocated { get; set; }
  public bool? LoanRepaymentScheduleId_IsProcessed { get; set; }
  public DateTime? LoanRepaymentScheduleId_ProcessedDate { get; set; }
  public bool? LoanRepaymentScheduleId_IsActive { get; set; }
  public string? LoanRepaymentScheduleId_CreatedByUserId { get; set; }
  public string? LoanRepaymentScheduleId_UpdatedByUserId { get; set; }
  public string? LoanRepaymentScheduleId_DeletedByUserId { get; set; }
  public bool? LoanRepaymentScheduleId_IsDeleted { get; set; }
  public string? LoanRepaymentScheduleId_Tags { get; set; }
  public string? LoanRepaymentScheduleId_Caption { get; set; }
  public decimal? LoanRepaymentScheduleId_ActualInterestAllocated { get; set; }
  public decimal? LoanRepaymentScheduleId_ActualInterestBalance { get; set; }
  public decimal? LoanRepaymentScheduleId_ActualPrincipalAllocated { get; set; }
  public decimal? LoanRepaymentScheduleId_ActualPrincipalBalance { get; set; }
  public string? PayrollDeductionScheduleItemId_PayrollDeductionScheduleId { get; set; }
  public string? PayrollDeductionScheduleItemId_BatchRefNo { get; set; }
  public string? PayrollDeductionScheduleItemId_MemberId { get; set; }
  public string? PayrollDeductionScheduleItemId_MemberName { get; set; }
  public string? PayrollDeductionScheduleItemId_AccountNo { get; set; }
  public decimal? PayrollDeductionScheduleItemId_Amount { get; set; }
  public string? PayrollDeductionScheduleItemId_PayrollCode { get; set; }
  public string? PayrollDeductionScheduleItemId_Narration { get; set; }
  public DateTime? PayrollDeductionScheduleItemId_PayrollDate { get; set; }
  public DateTime? PayrollDeductionScheduleItemId_AccountDueDate { get; set; }
  public string? PayrollDeductionScheduleItemId_CurrentStatus { get; set; }
  public string? PayrollDeductionScheduleItemId_DeductionType { get; set; }
  public string? PayrollDeductionScheduleItemId_LoanRepaymentScheduleId { get; set; }
  public string? PayrollDeductionScheduleItemId_SavingsAccountDeductionScheduleId { get; set; }
  public string? PayrollDeductionScheduleItemId_PayrollCronJobConfigId { get; set; }
  public string? PayrollDeductionScheduleItemId_SpecialDepositAccountDeductionScheduleId { get; set; }
  public bool? PayrollDeductionScheduleItemId_IsActive { get; set; }
  public string? PayrollDeductionScheduleItemId_CreatedByUserId { get; set; }
  public string? PayrollDeductionScheduleItemId_UpdatedByUserId { get; set; }
  public string? PayrollDeductionScheduleItemId_DeletedByUserId { get; set; }
  public bool? PayrollDeductionScheduleItemId_IsDeleted { get; set; }
  public string? PayrollDeductionScheduleItemId_Tags { get; set; }
  public string? PayrollDeductionScheduleItemId_Caption { get; set; }
  public string? LoanOffsetId_LoanAccountId { get; set; }
  public decimal? LoanOffsetId_OffsetAmount { get; set; }
  public decimal? LoanOffsetId_OldPrincipalBalance { get; set; }
  public decimal? LoanOffsetId_NewPrincipalBalance { get; set; }
  public decimal? LoanOffsetId_OldInterestBalance { get; set; }
  public decimal? LoanOffsetId_NewInterestBalance { get; set; }
  public decimal? LoanOffsetId_TotalOffsetCharges { get; set; }
  public bool? LoanOffsetId_IsLiquidated { get; set; }
  public string? LoanOffsetId_AllowedOffsetType { get; set; }
  public string? LoanOffsetId_LoanRepaymentMode { get; set; }
  public DateTimeOffset? LoanOffsetId_OffSetRepaymentDate { get; set; }
  public string? LoanOffsetId_SavingsAccountId { get; set; }
  public string? LoanOffsetId_SpecialDepositAccountId { get; set; }
  public string? LoanOffsetId_CustomerBankAccountId { get; set; }
  public int? LoanOffsetId_ModeOfPayment { get; set; }
  public string? LoanOffsetId_CustomerPaymentDocumentId { get; set; }
  public string? LoanOffsetId_TransactionJournalId { get; set; }
  public string? LoanOffsetId_ApprovalId { get; set; }
  public bool? LoanOffsetId_IsProcessed { get; set; }
  public DateTime? LoanOffsetId_ProcessedDate { get; set; }
  public string? LoanOffsetId_Status { get; set; }
  public bool? LoanOffsetId_IsActive { get; set; }
  public string? LoanOffsetId_CreatedByUserId { get; set; }
  public string? LoanOffsetId_UpdatedByUserId { get; set; }
  public string? LoanOffsetId_DeletedByUserId { get; set; }
  public bool? LoanOffsetId_IsDeleted { get; set; }
  public string? LoanOffsetId_Tags { get; set; }
  public string? LoanOffsetId_Caption { get; set; }
  public string? LoanOffsetId_RepaymentSchedules { get; set; }
  public string? ApprovalId_Module { get; set; }
  public string? ApprovalId_ApprovalType { get; set; }
  public string? ApprovalId_Status { get; set; }
  public int? ApprovalId_CurrentSequence { get; set; }
  public string? ApprovalId_ApprovalWorkflowId { get; set; }
  public string? ApprovalId_Payload { get; set; }
  public bool? ApprovalId_IsApprovalCompleted { get; set; }
  public string? ApprovalId_Comment { get; set; }
  public string? ApprovalId_EntityId { get; set; }
  public int? ApprovalId_TriedCount { get; set; }
  public bool? ApprovalId_IsActive { get; set; }
  public string? ApprovalId_CreatedByUserId { get; set; }
  public string? ApprovalId_UpdatedByUserId { get; set; }
  public string? ApprovalId_DeletedByUserId { get; set; }
  public bool? ApprovalId_IsDeleted { get; set; }
  public string? ApprovalId_Tags { get; set; }
  public string? ApprovalId_Caption { get; set; }
  public string? ApprovalId_ApprovalViewModelPayload { get; set; }
  public string? PaymentAccountId_LedgerAccountId { get; set; }
  public string? PaymentAccountId_BankId { get; set; }
  public string? PaymentAccountId_BranchName { get; set; }
  public string? PaymentAccountId_BranchAddress { get; set; }
  public string? PaymentAccountId_CurrencyId { get; set; }
  public string? PaymentAccountId_AccountName { get; set; }
  public string? PaymentAccountId_AccountNumber { get; set; }
  public string? PaymentAccountId_BVN { get; set; }
  public bool? PaymentAccountId_IsActive { get; set; }
  public string? PaymentAccountId_CreatedByUserId { get; set; }
  public string? PaymentAccountId_UpdatedByUserId { get; set; }
  public string? PaymentAccountId_DeletedByUserId { get; set; }
  public bool? PaymentAccountId_IsDeleted { get; set; }
  public string? PaymentAccountId_Tags { get; set; }
  public string? PaymentAccountId_Caption { get; set; }
  public string? CustomerBankAccountId_LedgerAccountId { get; set; }
  public string? CustomerBankAccountId_CustomerId { get; set; }
  public string? CustomerBankAccountId_BankId { get; set; }
  public string? CustomerBankAccountId_AccountName { get; set; }
  public string? CustomerBankAccountId_AccountNumber { get; set; }
  public string? CustomerBankAccountId_BVN { get; set; }
  public string? CustomerBankAccountId_Branch { get; set; }
  public bool? CustomerBankAccountId_IsActive { get; set; }
  public string? CustomerBankAccountId_CreatedByUserId { get; set; }
  public string? CustomerBankAccountId_UpdatedByUserId { get; set; }
  public string? CustomerBankAccountId_DeletedByUserId { get; set; }
  public bool? CustomerBankAccountId_IsDeleted { get; set; }
  public string? CustomerBankAccountId_Tags { get; set; }
  public string? CustomerBankAccountId_Caption { get; set; }
  public string? TransactionJournalId_TransactionNo { get; set; }
  public string? TransactionJournalId_Title { get; set; }
  public string? TransactionJournalId_TransactionType { get; set; }
  public string? TransactionJournalId_DocumentRef { get; set; }
  public string? TransactionJournalId_DocumentRefId { get; set; }
  public string? TransactionJournalId_PostingRef { get; set; }
  public string? TransactionJournalId_PostingRefId { get; set; }
  public string? TransactionJournalId_EntityRef { get; set; }
  public string? TransactionJournalId_EntityRefId { get; set; }
  public DateTime? TransactionJournalId_TransactionDate { get; set; }
  public bool? TransactionJournalId_IsPosted { get; set; }
  public string? TransactionJournalId_PostedByUserId { get; set; }
  public DateTime? TransactionJournalId_DatePosted { get; set; }
  public bool? TransactionJournalId_IsReversed { get; set; }
  public string? TransactionJournalId_ReversedByUserId { get; set; }
  public DateTime? TransactionJournalId_ReversalDate { get; set; }
  public string? TransactionJournalId_ApprovalId { get; set; }
  public DateTime? TransactionJournalId_ApprovalDate { get; set; }
  public string? TransactionJournalId_Memo { get; set; }
  public bool? TransactionJournalId_IsActive { get; set; }
  public string? TransactionJournalId_CreatedByUserId { get; set; }
  public string? TransactionJournalId_UpdatedByUserId { get; set; }
  public string? TransactionJournalId_DeletedByUserId { get; set; }
  public bool? TransactionJournalId_IsDeleted { get; set; }
  public string? TransactionJournalId_Tags { get; set; }
  public string? TransactionJournalId_Caption { get; set; }
}