namespace AP.ChevronCoop.Entities.Accounting.JournalEntries;

public class JournalEntryMasterView
{
    public long? RowNumber { get; set; }
    public string Id { get; set; }
    public string TransactionEntryNo { get; set; }
    public string TransactionJournalId { get; set; }
    public string AccountId { get; set; }
    public string EntryType { get; set; }
    public int DecimalPlaces { get; set; }
    public decimal Debit { get; set; }
    public decimal Credit { get; set; }
    public DateTime TransactionDate { get; set; }
    public bool IsPosted { get; set; }
    public string? PostedByUserName { get; set; }
    public DateTime? DatePosted { get; set; }
    public bool IsReversed { get; set; }
    public string? ReversedByUserName { get; set; }
    public DateTime? ReversalDate { get; set; }
    public string? Memo { get; set; }
    public string? Description { get; set; }
    public bool IsActive { get; set; }
    public string? CreatedByUserId { get; set; }
    public DateTimeOffset? DateCreated { get; set; }
    public string? UpdatedByUserId { get; set; }
    public DateTimeOffset? DateUpdated { get; set; }
    public string? DeletedByUserId { get; set; }
    public bool IsDeleted { get; set; }
    public DateTimeOffset? DateDeleted { get; set; }
    public Guid RowVersion { get; set; }
    public string? FullText { get; set; }
    public string? Tags { get; set; }
    public string? Caption { get; set; }
    public string? TransactionJournalId_TransactionNo { get; set; }
    public string? TransactionJournalId_Title { get; set; }
    public string? TransactionJournalId_TransactionType { get; set; }
    public string? TransactionJournalId_DocumentRef { get; set; }
    public string? TransactionJournalId_DocumentRefId { get; set; }
    public string? TransactionJournalId_PostingRef { get; set; }
    public string? TransactionJournalId_PostingRefId { get; set; }
    public string? TransactionJournalId_EntityRef { get; set; }
    public string? TransactionJournalId_EntityRefId { get; set; }
    public DateTime? TransactionJournalId_TransactionDate { get; set; }
    public bool? TransactionJournalId_IsPosted { get; set; }
    public string? TransactionJournalId_PostedByUserId { get; set; }
    public DateTime? TransactionJournalId_DatePosted { get; set; }
    public bool? TransactionJournalId_IsReversed { get; set; }
    public string? TransactionJournalId_ReversedByUserId { get; set; }
    public DateTime? TransactionJournalId_ReversalDate { get; set; }
    public string? TransactionJournalId_ApprovalId { get; set; }
    public DateTime? TransactionJournalId_ApprovalDate { get; set; }
    public string? TransactionJournalId_Memo { get; set; }
    public bool? TransactionJournalId_IsActive { get; set; }
    public string? TransactionJournalId_CreatedByUserId { get; set; }
    public string? TransactionJournalId_UpdatedByUserId { get; set; }
    public string? TransactionJournalId_DeletedByUserId { get; set; }
    public bool? TransactionJournalId_IsDeleted { get; set; }
    public string? TransactionJournalId_Tags { get; set; }
    public string? TransactionJournalId_Caption { get; set; }
    public string? AccountId_AccountType { get; set; }
    public string? AccountId_UOM { get; set; }
    public string? AccountId_CurrencyId { get; set; }
    public string? AccountId_Code { get; set; }
    public string? AccountId_Name { get; set; }
    public string? AccountId_ParentId { get; set; }
    public decimal? AccountId_ClearedBalance { get; set; }
    public decimal? AccountId_UnclearedBalance { get; set; }
    public decimal? AccountId_LedgerBalance { get; set; }
    public decimal? AccountId_AvailableBalance { get; set; }
    public bool? AccountId_IsOfficeAccount { get; set; }
    public bool? AccountId_AllowManualEntry { get; set; }
    public bool? AccountId_IsClosed { get; set; }
    public DateTime? AccountId_DateClosed { get; set; }
    public string? AccountId_ClosedByUserName { get; set; }
    public bool? AccountId_IsActive { get; set; }
    public string? AccountId_CreatedByUserId { get; set; }
    public string? AccountId_UpdatedByUserId { get; set; }
    public string? AccountId_DeletedByUserId { get; set; }
    public bool? AccountId_IsDeleted { get; set; }
    public string? AccountId_Tags { get; set; }
    public string? AccountId_Caption { get; set; }
}