namespace AP.ChevronCoop.Entities.Security.MemberProfiles.MemberBankAccounts;

public class MemberBankAccountMasterView
{
    public long? RowNumber { get; set; }
    public string Id { get; set; }
    public string? ProfileId { get; set; }
    public string? BankId { get; set; }
    public string AccountName { get; set; }
    public string AccountNumber { get; set; }
    public string? BVN { get; set; }
    public string? Branch { get; set; }
    public string? Description { get; set; }
    public bool IsActive { get; set; }
    public string? CreatedByUserId { get; set; }
    public DateTimeOffset? DateCreated { get; set; }
    public string? UpdatedByUserId { get; set; }
    public DateTimeOffset? DateUpdated { get; set; }
    public string? DeletedByUserId { get; set; }
    public bool IsDeleted { get; set; }
    public DateTimeOffset? DateDeleted { get; set; }
    public Guid RowVersion { get; set; }
    public string? FullText { get; set; }
    public string? Tags { get; set; }
    public string? Caption { get; set; }
    public string? ProfileId_ApplicationUserId { get; set; }
    public int? ProfileId_YearsOfService { get; set; }
    public bool? ProfileId_IsKycStarted { get; set; }
    public bool? ProfileId_IsKycCompleted { get; set; }
    public DateTime? ProfileId_KycStartDate { get; set; }
    public DateTime? ProfileId_KycCompletedDate { get; set; }
    public string? ProfileId_Status { get; set; }
    public string? ProfileId_MemberType { get; set; }
    public string? ProfileId_Gender { get; set; }
    public string? ProfileId_ProfileImageUrl { get; set; }
    public string? ProfileId_PassportUrl { get; set; }
    public string? ProfileId_IdentificationType { get; set; }
    public string? ProfileId_IdentificationNumber { get; set; }
    public string? ProfileId_IdentificationUrl { get; set; }
    public bool? ProfileId_KycSubmitted { get; set; }
    public DateTime? ProfileId_KycSubmittedOn { get; set; }
    public bool? ProfileId_KycApproved { get; set; }
    public DateTime? ProfileId_KycApprovedOn { get; set; }
    public bool? ProfileId_KycApprovedBy { get; set; }
    public string? ProfileId_FirstName { get; set; }
    public string? ProfileId_LastName { get; set; }
    public string? ProfileId_MiddleName { get; set; }
    public string? ProfileId_DepartmentId { get; set; }
    public string? ProfileId_MembershipId { get; set; }
    public string? ProfileId_CAI { get; set; }
    public string? ProfileId_RetireeNumber { get; set; }
    public string? ProfileId_StateOfOrigin { get; set; }
    public string? ProfileId_PrimaryEmail { get; set; }
    public string? ProfileId_SecondaryEmail { get; set; }
    public string? ProfileId_PrimaryPhone { get; set; }
    public string? ProfileId_SecondaryPhone { get; set; }
    public string? ProfileId_ResidentialAddress { get; set; }
    public string? ProfileId_OfficeAddress { get; set; }
    public string? ProfileId_Rank { get; set; }
    public bool? ProfileId_SwitchToRetireeRequested { get; set; }
    public string? ProfileId_JobRole { get; set; }
    public DateTimeOffset? ProfileId_DOB { get; set; }
    public string? ProfileId_Address { get; set; }
    public string? ProfileId_Country { get; set; }
    public string? ProfileId_State { get; set; }
    public bool? ProfileId_IsActive { get; set; }
    public string? ProfileId_CreatedByUserId { get; set; }
    public string? ProfileId_UpdatedByUserId { get; set; }
    public string? ProfileId_DeletedByUserId { get; set; }
    public bool? ProfileId_IsDeleted { get; set; }
    public string? ProfileId_Tags { get; set; }
    public string? ProfileId_Caption { get; set; }
    public string? BankId_Code { get; set; }
    public string? BankId_SortCode { get; set; }
    public string? BankId_Name { get; set; }
    public string? BankId_Address { get; set; }
    public string? BankId_ContactName { get; set; }
    public string? BankId_ContactDetails { get; set; }
    public bool? BankId_IsActive { get; set; }
    public string? BankId_CreatedByUserId { get; set; }
    public string? BankId_UpdatedByUserId { get; set; }
    public string? BankId_DeletedByUserId { get; set; }
    public bool? BankId_IsDeleted { get; set; }
    public string? BankId_Tags { get; set; }
    public string? BankId_Caption { get; set; }

    public string Details => $"{AccountNumber} - {BankId_Name} ({AccountName})";
}