namespace AP.ChevronCoop.Entities.Loans.LoanRepaymentSchedules;

public class LoanRepaymentScheduleMasterView
{
  public long? RowNumber { get; set; }
  public string Id { get; set; }
  public string LoanAccountId { get; set; }
  public int RepaymentNo { get; set; }
  public string BatchRefNo { get; set; }
  public string TenureUnit { get; set; }
  public decimal TenureValue { get; set; }
  public DateTime PeriodStartDate { get; set; }
  public DateTime DueDate { get; set; }
  public int? DaysInPeriod { get; set; }
  public decimal PeriodPayment { get; set; }
  public decimal CumulativeTotal { get; set; }
  public decimal TotalBalance { get; set; }
  public decimal PeriodPrincipal { get; set; }
  public decimal CumulativePrincipal { get; set; }
  public decimal PrincipalBalance { get; set; }
  public decimal PeriodInterest { get; set; }
  public decimal CumulativeInterest { get; set; }
  public decimal InterestBalance { get; set; }
  public bool IsPaid { get; set; }
  public bool IsPrincipalAllocated { get; set; }
  public bool IsInterestAllocated { get; set; }
  public bool IsProcessed { get; set; }
  public DateTime? ProcessedDate { get; set; }
  public string? Description { get; set; }
  public bool IsActive { get; set; }
  public string? CreatedByUserId { get; set; }
  public DateTimeOffset? DateCreated { get; set; }
  public string? UpdatedByUserId { get; set; }
  public DateTimeOffset? DateUpdated { get; set; }
  public string? DeletedByUserId { get; set; }
  public bool IsDeleted { get; set; }
  public DateTimeOffset? DateDeleted { get; set; }
  public Guid RowVersion { get; set; }
  public string? FullText { get; set; }
  public string? Tags { get; set; }
  public string? Caption { get; set; }
  public decimal ActualInterestAllocated { get; set; }
  public decimal ActualInterestBalance { get; set; }
  public decimal ActualPrincipalAllocated { get; set; }
  public decimal ActualPrincipalBalance { get; set; }
  public string? LoanAccountId_AccountNo { get; set; }
  public string? LoanAccountId_LoanApplicationId { get; set; }
  public string? LoanAccountId_CustomerId { get; set; }
  public string? LoanAccountId_PrincipalBalanceAccountId { get; set; }
  public string? LoanAccountId_PrincipalLossAccountId { get; set; }
  public string? LoanAccountId_EarnedInterestAccountId { get; set; }
  public string? LoanAccountId_InterestBalanceAccountId { get; set; }
  public string? LoanAccountId_UnearnedInterestAccountId { get; set; }
  public string? LoanAccountId_InterestLossAccountId { get; set; }
  public string? LoanAccountId_InterestWaivedAccountId { get; set; }
  public string? LoanAccountId_ChargesAccruedAccountId { get; set; }
  public string? LoanAccountId_ChargesIncomeAccountId { get; set; }
  public string? LoanAccountId_ChargesWaivedAccountId { get; set; }
  public decimal? LoanAccountId_Principal { get; set; }
  public string? LoanAccountId_TenureUnit { get; set; }
  public decimal? LoanAccountId_TenureValue { get; set; }
  public DateTimeOffset? LoanAccountId_RepaymentCommencementDate { get; set; }
  public bool? LoanAccountId_UseSpecialDeposit { get; set; }
  public string? LoanAccountId_SpecialDepositAccountId { get; set; }
  public string? LoanAccountId_DestinationAccountId { get; set; }
  public bool? LoanAccountId_IsClosed { get; set; }
  public DateTime? LoanAccountId_DateClosed { get; set; }
  public string? LoanAccountId_ClosedByUserId { get; set; }
  public string? LoanAccountId_LoanTopupId { get; set; }
  public string? LoanAccountId_InterestPayoutAccountId { get; set; }
  public bool? LoanAccountId_IsActive { get; set; }
  public string? LoanAccountId_CreatedByUserId { get; set; }
  public string? LoanAccountId_UpdatedByUserId { get; set; }
  public string? LoanAccountId_DeletedByUserId { get; set; }
  public bool? LoanAccountId_IsDeleted { get; set; }
  public string? LoanAccountId_Tags { get; set; }
  public string? LoanAccountId_Caption { get; set; }
  public string? LoanAccountId_LoanCreationType { get; set; }
  public string? LoanAccountId_ParentAccountId { get; set; }
  public string? LoanAccountId_RootParentAccountId { get; set; }
}