namespace AP.ChevronCoop.Entities.Loans.LoanDisbursementCharges;

public class LoanDisbursementChargeMasterView
{
  public long? RowNumber { get; set; }
  public string Id { get; set; }
  public string LoanDisbursementId { get; set; }
  public string DisbursementChargeId { get; set; }
  public string ChargeType { get; set; }
  public decimal TotalCharge { get; set; }
  public string? TransactionJournalId { get; set; }
  public string? Description { get; set; }
  public bool IsActive { get; set; }
  public string? CreatedByUserId { get; set; }
  public DateTimeOffset? DateCreated { get; set; }
  public string? UpdatedByUserId { get; set; }
  public DateTimeOffset? DateUpdated { get; set; }
  public string? DeletedByUserId { get; set; }
  public bool IsDeleted { get; set; }
  public DateTimeOffset? DateDeleted { get; set; }
  public Guid RowVersion { get; set; }
  public string? FullText { get; set; }
  public string? Tags { get; set; }
  public string? Caption { get; set; }
  public string? LoanDisbursementId_LoanAccountId { get; set; }
  public decimal? LoanDisbursementId_Amount { get; set; }
  public string? LoanDisbursementId_ApprovedByUserId { get; set; }
  public string? LoanDisbursementId_DisbursedByUserId { get; set; }
  public string? LoanDisbursementId_DisbursementStatus { get; set; }
  public string? LoanDisbursementId_DisbursementAccountId { get; set; }
  public DateTimeOffset? LoanDisbursementId_DisbursementDate { get; set; }
  public string? LoanDisbursementId_DisbursementMode { get; set; }
  public string? LoanDisbursementId_SpecialDepositAccountId { get; set; }
  public string? LoanDisbursementId_CustomerBankAccountId { get; set; }
  public string? LoanDisbursementId_TransactionJournalId { get; set; }
  public string? LoanDisbursementId_ApprovalId { get; set; }
  public DateTimeOffset? LoanDisbursementId_ApprovalDate { get; set; }
  public bool? LoanDisbursementId_IsProcessed { get; set; }
  public DateTime? LoanDisbursementId_ProcessedDate { get; set; }
  public string? LoanDisbursementId_Status { get; set; }
  public bool? LoanDisbursementId_IsActive { get; set; }
  public string? LoanDisbursementId_CreatedByUserId { get; set; }
  public string? LoanDisbursementId_UpdatedByUserId { get; set; }
  public string? LoanDisbursementId_DeletedByUserId { get; set; }
  public bool? LoanDisbursementId_IsDeleted { get; set; }
  public string? LoanDisbursementId_Tags { get; set; }
  public string? LoanDisbursementId_Caption { get; set; }
  public string? LoanDisbursementId_TransactionType { get; set; }
  public string? DisbursementChargeId_Code { get; set; }
  public string? DisbursementChargeId_Name { get; set; }
  public string? DisbursementChargeId_Method { get; set; }
  public string? DisbursementChargeId_Target { get; set; }
  public string? DisbursementChargeId_CalculationMethod { get; set; }
  public string? DisbursementChargeId_CurrencyId { get; set; }
  public decimal? DisbursementChargeId_ChargeValue { get; set; }
  public decimal? DisbursementChargeId_MaximumCharge { get; set; }
  public decimal? DisbursementChargeId_MinimimumCharge { get; set; }
  public bool? DisbursementChargeId_IsActive { get; set; }
  public string? DisbursementChargeId_CreatedByUserId { get; set; }
  public string? DisbursementChargeId_UpdatedByUserId { get; set; }
  public string? DisbursementChargeId_DeletedByUserId { get; set; }
  public bool? DisbursementChargeId_IsDeleted { get; set; }
  public string? DisbursementChargeId_Tags { get; set; }
  public string? DisbursementChargeId_Caption { get; set; }
  public string? TransactionJournalId_TransactionNo { get; set; }
  public string? TransactionJournalId_Title { get; set; }
  public string? TransactionJournalId_TransactionType { get; set; }
  public string? TransactionJournalId_DocumentRef { get; set; }
  public string? TransactionJournalId_DocumentRefId { get; set; }
  public string? TransactionJournalId_PostingRef { get; set; }
  public string? TransactionJournalId_PostingRefId { get; set; }
  public string? TransactionJournalId_EntityRef { get; set; }
  public string? TransactionJournalId_EntityRefId { get; set; }
  public DateTime? TransactionJournalId_TransactionDate { get; set; }
  public bool? TransactionJournalId_IsPosted { get; set; }
  public string? TransactionJournalId_PostedByUserId { get; set; }
  public DateTime? TransactionJournalId_DatePosted { get; set; }
  public bool? TransactionJournalId_IsReversed { get; set; }
  public string? TransactionJournalId_ReversedByUserId { get; set; }
  public DateTime? TransactionJournalId_ReversalDate { get; set; }
  public string? TransactionJournalId_ApprovalId { get; set; }
  public DateTime? TransactionJournalId_ApprovalDate { get; set; }
  public string? TransactionJournalId_Memo { get; set; }
  public bool? TransactionJournalId_IsActive { get; set; }
  public string? TransactionJournalId_CreatedByUserId { get; set; }
  public string? TransactionJournalId_UpdatedByUserId { get; set; }
  public string? TransactionJournalId_DeletedByUserId { get; set; }
  public bool? TransactionJournalId_IsDeleted { get; set; }
  public string? TransactionJournalId_Tags { get; set; }
  public string? TransactionJournalId_Caption { get; set; }
}