namespace AP.ChevronCoop.Entities.Loans.LoanRepaymentCharges;

public class LoanRepaymentChargeMasterView
{
  public long? RowNumber { get; set; }
  public string Id { get; set; }
  public string LoanRepaymentId { get; set; }
  public string RepaymentChargeId { get; set; }
  public string ChargeType { get; set; }
  public decimal TotalCharge { get; set; }
  public string? TransactionJournalId { get; set; }
  public string? LoanRepaymentId1 { get; set; }
  public string? Description { get; set; }
  public bool IsActive { get; set; }
  public string? CreatedByUserId { get; set; }
  public DateTimeOffset? DateCreated { get; set; }
  public string? UpdatedByUserId { get; set; }
  public DateTimeOffset? DateUpdated { get; set; }
  public string? DeletedByUserId { get; set; }
  public bool IsDeleted { get; set; }
  public DateTimeOffset? DateDeleted { get; set; }
  public Guid RowVersion { get; set; }
  public string? FullText { get; set; }
  public string? Tags { get; set; }
  public string? Caption { get; set; }
  public string? LoanRepaymentId_RepaymentMode { get; set; }
  public string? LoanRepaymentId_LoanAccountId { get; set; }
  public string? LoanRepaymentId_LoanRepaymentScheduleId { get; set; }
  public string? LoanRepaymentId_PayrollDeductionScheduleItemId { get; set; }
  public string? LoanRepaymentId_LoanOffsetId { get; set; }
  public string? LoanRepaymentId_ApprovalId { get; set; }
  public decimal? LoanRepaymentId_Amount { get; set; }
  public decimal? LoanRepaymentId_Principal { get; set; }
  public decimal? LoanRepaymentId_Interest { get; set; }
  public DateTimeOffset? LoanRepaymentId_PeriodStartDate { get; set; }
  public DateTimeOffset? LoanRepaymentId_RepaymentDate { get; set; }
  public string? LoanRepaymentId_PaymentAccountId { get; set; }
  public string? LoanRepaymentId_CustomerBankAccountId { get; set; }
  public string? LoanRepaymentId_TransactionJournalId { get; set; }
  public bool? LoanRepaymentId_IsProcessed { get; set; }
  public DateTime? LoanRepaymentId_ProcessedDate { get; set; }
  public string? LoanRepaymentId_Status { get; set; }
  public bool? LoanRepaymentId_IsActive { get; set; }
  public string? LoanRepaymentId_CreatedByUserId { get; set; }
  public string? LoanRepaymentId_UpdatedByUserId { get; set; }
  public string? LoanRepaymentId_DeletedByUserId { get; set; }
  public bool? LoanRepaymentId_IsDeleted { get; set; }
  public string? LoanRepaymentId_Tags { get; set; }
  public string? LoanRepaymentId_Caption { get; set; }
  public string? RepaymentChargeId_Code { get; set; }
  public string? RepaymentChargeId_Name { get; set; }
  public string? RepaymentChargeId_Method { get; set; }
  public string? RepaymentChargeId_Target { get; set; }
  public string? RepaymentChargeId_CalculationMethod { get; set; }
  public string? RepaymentChargeId_CurrencyId { get; set; }
  public decimal? RepaymentChargeId_ChargeValue { get; set; }
  public decimal? RepaymentChargeId_MaximumCharge { get; set; }
  public decimal? RepaymentChargeId_MinimimumCharge { get; set; }
  public bool? RepaymentChargeId_IsActive { get; set; }
  public string? RepaymentChargeId_CreatedByUserId { get; set; }
  public string? RepaymentChargeId_UpdatedByUserId { get; set; }
  public string? RepaymentChargeId_DeletedByUserId { get; set; }
  public bool? RepaymentChargeId_IsDeleted { get; set; }
  public string? RepaymentChargeId_Tags { get; set; }
  public string? RepaymentChargeId_Caption { get; set; }
  public string? TransactionJournalId_TransactionNo { get; set; }
  public string? TransactionJournalId_Title { get; set; }
  public string? TransactionJournalId_TransactionType { get; set; }
  public string? TransactionJournalId_DocumentRef { get; set; }
  public string? TransactionJournalId_DocumentRefId { get; set; }
  public string? TransactionJournalId_PostingRef { get; set; }
  public string? TransactionJournalId_PostingRefId { get; set; }
  public string? TransactionJournalId_EntityRef { get; set; }
  public string? TransactionJournalId_EntityRefId { get; set; }
  public DateTime? TransactionJournalId_TransactionDate { get; set; }
  public bool? TransactionJournalId_IsPosted { get; set; }
  public string? TransactionJournalId_PostedByUserId { get; set; }
  public DateTime? TransactionJournalId_DatePosted { get; set; }
  public bool? TransactionJournalId_IsReversed { get; set; }
  public string? TransactionJournalId_ReversedByUserId { get; set; }
  public DateTime? TransactionJournalId_ReversalDate { get; set; }
  public string? TransactionJournalId_ApprovalId { get; set; }
  public DateTime? TransactionJournalId_ApprovalDate { get; set; }
  public string? TransactionJournalId_Memo { get; set; }
  public bool? TransactionJournalId_IsActive { get; set; }
  public string? TransactionJournalId_CreatedByUserId { get; set; }
  public string? TransactionJournalId_UpdatedByUserId { get; set; }
  public string? TransactionJournalId_DeletedByUserId { get; set; }
  public bool? TransactionJournalId_IsDeleted { get; set; }
  public string? TransactionJournalId_Tags { get; set; }
  public string? TransactionJournalId_Caption { get; set; }
  public string? LoanRepaymentId1_RepaymentMode { get; set; }
  public string? LoanRepaymentId1_LoanAccountId { get; set; }
  public string? LoanRepaymentId1_LoanRepaymentScheduleId { get; set; }
  public string? LoanRepaymentId1_PayrollDeductionScheduleItemId { get; set; }
  public string? LoanRepaymentId1_LoanOffsetId { get; set; }
  public string? LoanRepaymentId1_ApprovalId { get; set; }
  public decimal? LoanRepaymentId1_Amount { get; set; }
  public decimal? LoanRepaymentId1_Principal { get; set; }
  public decimal? LoanRepaymentId1_Interest { get; set; }
  public DateTimeOffset? LoanRepaymentId1_PeriodStartDate { get; set; }
  public DateTimeOffset? LoanRepaymentId1_RepaymentDate { get; set; }
  public string? LoanRepaymentId1_PaymentAccountId { get; set; }
  public string? LoanRepaymentId1_CustomerBankAccountId { get; set; }
  public string? LoanRepaymentId1_TransactionJournalId { get; set; }
  public bool? LoanRepaymentId1_IsProcessed { get; set; }
  public DateTime? LoanRepaymentId1_ProcessedDate { get; set; }
  public string? LoanRepaymentId1_Status { get; set; }
  public bool? LoanRepaymentId1_IsActive { get; set; }
  public string? LoanRepaymentId1_CreatedByUserId { get; set; }
  public string? LoanRepaymentId1_UpdatedByUserId { get; set; }
  public string? LoanRepaymentId1_DeletedByUserId { get; set; }
  public bool? LoanRepaymentId1_IsDeleted { get; set; }
  public string? LoanRepaymentId1_Tags { get; set; }
  public string? LoanRepaymentId1_Caption { get; set; }
}