using System.ComponentModel.DataAnnotations.Schema;

namespace AP.ChevronCoop.Entities.Deposits.Products.DepositProducts;

[Table(nameof(DepositProductMasterView), Schema = "Deposits")]
public class DepositProductMasterView
{
    public long? RowNumber { get; set; }
    public string Id { get; set; }
    public string Code { get; set; }
    public string Name { get; set; }
    public string ShortName { get; set; }
    public string? ApprovalWorkflowId { get; set; }
    public string? ApprovalId { get; set; }
    public int MinimumAge { get; set; }
    public int MaximumAge { get; set; }
    public string Tenure { get; set; }
    public decimal TenureValue { get; set; }
    public string Status { get; set; }
    public string PublicationType { get; set; }
    public string? PublishedByUserId { get; set; }
    public string DefaultCurrencyId { get; set; }
    public string? BankDepositAccountId { get; set; }
    public string ProductDepositAccountId { get; set; }
    public string ChargesIncomeAccountId { get; set; }
    public string ChargesAccrualAccountId { get; set; }
    public string ChargesWaivedAccountId { get; set; }
    public string InterestPayableAccountId { get; set; }
    public string InterestPayoutAccountId { get; set; }
    public bool IsInterestEnabled { get; set; }
    public decimal? MinimumContributionRegular { get; set; }
    public decimal? MinimumContributionRetiree { get; set; }
    public string ProductType { get; set; }
    public string? Description { get; set; }
    public bool IsActive { get; set; }
    public string? CreatedByUserId { get; set; }
    public DateTimeOffset? DateCreated { get; set; }
    public string? UpdatedByUserId { get; set; }
    public DateTimeOffset? DateUpdated { get; set; }
    public string? DeletedByUserId { get; set; }
    public bool IsDeleted { get; set; }
    public DateTimeOffset? DateDeleted { get; set; }
    public Guid RowVersion { get; set; }
    public string? FullText { get; set; }
    public string? Tags { get; set; }
    public string? Caption { get; set; }
    public bool? IsDefaultProduct { get; set; }
    public string? ApprovalWorkflowId_WorkflowName { get; set; }
    public bool? ApprovalWorkflowId_IsDefaultApprovalWorkflow { get; set; }
    public int? ApprovalWorkflowId_RequiredApprovers { get; set; }
    public int? ApprovalWorkflowId_RequiredGroups { get; set; }
    public bool? ApprovalWorkflowId_IsActive { get; set; }
    public string? ApprovalWorkflowId_CreatedByUserId { get; set; }
    public string? ApprovalWorkflowId_UpdatedByUserId { get; set; }
    public string? ApprovalWorkflowId_DeletedByUserId { get; set; }
    public bool? ApprovalWorkflowId_IsDeleted { get; set; }
    public string? ApprovalWorkflowId_Tags { get; set; }
    public string? ApprovalWorkflowId_Caption { get; set; }
    public string? ApprovalId_Module { get; set; }
    public string? ApprovalId_ApprovalType { get; set; }
    public string? ApprovalId_Status { get; set; }
    public int? ApprovalId_CurrentSequence { get; set; }
    public string? ApprovalId_ApprovalWorkflowId { get; set; }
    public string? ApprovalId_Payload { get; set; }
    public bool? ApprovalId_IsApprovalCompleted { get; set; }
    public string? ApprovalId_Comment { get; set; }
    public string? ApprovalId_EntityId { get; set; }
    public int? ApprovalId_TriedCount { get; set; }
    public bool? ApprovalId_IsActive { get; set; }
    public string? ApprovalId_CreatedByUserId { get; set; }
    public string? ApprovalId_UpdatedByUserId { get; set; }
    public string? ApprovalId_DeletedByUserId { get; set; }
    public bool? ApprovalId_IsDeleted { get; set; }
    public string? ApprovalId_Tags { get; set; }
    public string? ApprovalId_Caption { get; set; }
    public string? ApprovalId_ApprovalViewModelPayload { get; set; }
    public string? PublishedByUserId_AdObjectId { get; set; }
    public bool? PublishedByUserId_IsAdmin { get; set; }
    public string? PublishedByUserId_SecondaryPhone { get; set; }
    public bool? PublishedByUserId_SecondaryPhoneConfirmed { get; set; }
    public string? PublishedByUserId_UserName { get; set; }
    public string? PublishedByUserId_NormalizedUserName { get; set; }
    public string? PublishedByUserId_Email { get; set; }
    public string? PublishedByUserId_NormalizedEmail { get; set; }
    public bool? PublishedByUserId_EmailConfirmed { get; set; }
    public string? PublishedByUserId_PasswordHash { get; set; }
    public string? PublishedByUserId_SecurityStamp { get; set; }
    public string? PublishedByUserId_ConcurrencyStamp { get; set; }
    public string? PublishedByUserId_PhoneNumber { get; set; }
    public bool? PublishedByUserId_PhoneNumberConfirmed { get; set; }
    public bool? PublishedByUserId_TwoFactorEnabled { get; set; }
    public DateTimeOffset? PublishedByUserId_LockoutEnd { get; set; }
    public bool? PublishedByUserId_LockoutEnabled { get; set; }
    public int? PublishedByUserId_AccessFailedCount { get; set; }
    public string? DefaultCurrencyId_Code { get; set; }
    public string? DefaultCurrencyId_Name { get; set; }
    public string? DefaultCurrencyId_Symbol { get; set; }
    public string? DefaultCurrencyId_IsoSymbol { get; set; }
    public int? DefaultCurrencyId_DecimalPlaces { get; set; }
    public string? DefaultCurrencyId_Format { get; set; }
    public bool? DefaultCurrencyId_IsActive { get; set; }
    public string? DefaultCurrencyId_CreatedByUserId { get; set; }
    public string? DefaultCurrencyId_UpdatedByUserId { get; set; }
    public string? DefaultCurrencyId_DeletedByUserId { get; set; }
    public bool? DefaultCurrencyId_IsDeleted { get; set; }
    public string? DefaultCurrencyId_Tags { get; set; }
    public string? DefaultCurrencyId_Caption { get; set; }
    public string? BankDepositAccountId_LedgerAccountId { get; set; }
    public string? BankDepositAccountId_BankId { get; set; }
    public string? BankDepositAccountId_BranchName { get; set; }
    public string? BankDepositAccountId_BranchAddress { get; set; }
    public string? BankDepositAccountId_CurrencyId { get; set; }
    public string? BankDepositAccountId_AccountName { get; set; }
    public string? BankDepositAccountId_AccountNumber { get; set; }
    public string? BankDepositAccountId_BVN { get; set; }
    public bool? BankDepositAccountId_IsActive { get; set; }
    public string? BankDepositAccountId_CreatedByUserId { get; set; }
    public string? BankDepositAccountId_UpdatedByUserId { get; set; }
    public string? BankDepositAccountId_DeletedByUserId { get; set; }
    public bool? BankDepositAccountId_IsDeleted { get; set; }
    public string? BankDepositAccountId_Tags { get; set; }
    public string? BankDepositAccountId_Caption { get; set; }
    public string? ProductDepositAccountId_AccountType { get; set; }
    public string? ProductDepositAccountId_UOM { get; set; }
    public string? ProductDepositAccountId_CurrencyId { get; set; }
    public string? ProductDepositAccountId_Code { get; set; }
    public string? ProductDepositAccountId_Name { get; set; }
    public string? ProductDepositAccountId_ParentId { get; set; }
    public decimal? ProductDepositAccountId_ClearedBalance { get; set; }
    public decimal? ProductDepositAccountId_UnclearedBalance { get; set; }
    public decimal? ProductDepositAccountId_LedgerBalance { get; set; }
    public decimal? ProductDepositAccountId_AvailableBalance { get; set; }
    public bool? ProductDepositAccountId_IsOfficeAccount { get; set; }
    public bool? ProductDepositAccountId_AllowManualEntry { get; set; }
    public bool? ProductDepositAccountId_IsClosed { get; set; }
    public DateTime? ProductDepositAccountId_DateClosed { get; set; }
    public string? ProductDepositAccountId_ClosedByUserName { get; set; }
    public bool? ProductDepositAccountId_IsActive { get; set; }
    public string? ProductDepositAccountId_CreatedByUserId { get; set; }
    public string? ProductDepositAccountId_UpdatedByUserId { get; set; }
    public string? ProductDepositAccountId_DeletedByUserId { get; set; }
    public bool? ProductDepositAccountId_IsDeleted { get; set; }
    public string? ProductDepositAccountId_Tags { get; set; }
    public string? ProductDepositAccountId_Caption { get; set; }
    public string? ChargesIncomeAccountId_AccountType { get; set; }
    public string? ChargesIncomeAccountId_UOM { get; set; }
    public string? ChargesIncomeAccountId_CurrencyId { get; set; }
    public string? ChargesIncomeAccountId_Code { get; set; }
    public string? ChargesIncomeAccountId_Name { get; set; }
    public string? ChargesIncomeAccountId_ParentId { get; set; }
    public decimal? ChargesIncomeAccountId_ClearedBalance { get; set; }
    public decimal? ChargesIncomeAccountId_UnclearedBalance { get; set; }
    public decimal? ChargesIncomeAccountId_LedgerBalance { get; set; }
    public decimal? ChargesIncomeAccountId_AvailableBalance { get; set; }
    public bool? ChargesIncomeAccountId_IsOfficeAccount { get; set; }
    public bool? ChargesIncomeAccountId_AllowManualEntry { get; set; }
    public bool? ChargesIncomeAccountId_IsClosed { get; set; }
    public DateTime? ChargesIncomeAccountId_DateClosed { get; set; }
    public string? ChargesIncomeAccountId_ClosedByUserName { get; set; }
    public bool? ChargesIncomeAccountId_IsActive { get; set; }
    public string? ChargesIncomeAccountId_CreatedByUserId { get; set; }
    public string? ChargesIncomeAccountId_UpdatedByUserId { get; set; }
    public string? ChargesIncomeAccountId_DeletedByUserId { get; set; }
    public bool? ChargesIncomeAccountId_IsDeleted { get; set; }
    public string? ChargesIncomeAccountId_Tags { get; set; }
    public string? ChargesIncomeAccountId_Caption { get; set; }
    public string? ChargesAccrualAccountId_AccountType { get; set; }
    public string? ChargesAccrualAccountId_UOM { get; set; }
    public string? ChargesAccrualAccountId_CurrencyId { get; set; }
    public string? ChargesAccrualAccountId_Code { get; set; }
    public string? ChargesAccrualAccountId_Name { get; set; }
    public string? ChargesAccrualAccountId_ParentId { get; set; }
    public decimal? ChargesAccrualAccountId_ClearedBalance { get; set; }
    public decimal? ChargesAccrualAccountId_UnclearedBalance { get; set; }
    public decimal? ChargesAccrualAccountId_LedgerBalance { get; set; }
    public decimal? ChargesAccrualAccountId_AvailableBalance { get; set; }
    public bool? ChargesAccrualAccountId_IsOfficeAccount { get; set; }
    public bool? ChargesAccrualAccountId_AllowManualEntry { get; set; }
    public bool? ChargesAccrualAccountId_IsClosed { get; set; }
    public DateTime? ChargesAccrualAccountId_DateClosed { get; set; }
    public string? ChargesAccrualAccountId_ClosedByUserName { get; set; }
    public bool? ChargesAccrualAccountId_IsActive { get; set; }
    public string? ChargesAccrualAccountId_CreatedByUserId { get; set; }
    public string? ChargesAccrualAccountId_UpdatedByUserId { get; set; }
    public string? ChargesAccrualAccountId_DeletedByUserId { get; set; }
    public bool? ChargesAccrualAccountId_IsDeleted { get; set; }
    public string? ChargesAccrualAccountId_Tags { get; set; }
    public string? ChargesAccrualAccountId_Caption { get; set; }
    public string? ChargesWaivedAccountId_AccountType { get; set; }
    public string? ChargesWaivedAccountId_UOM { get; set; }
    public string? ChargesWaivedAccountId_CurrencyId { get; set; }
    public string? ChargesWaivedAccountId_Code { get; set; }
    public string? ChargesWaivedAccountId_Name { get; set; }
    public string? ChargesWaivedAccountId_ParentId { get; set; }
    public decimal? ChargesWaivedAccountId_ClearedBalance { get; set; }
    public decimal? ChargesWaivedAccountId_UnclearedBalance { get; set; }
    public decimal? ChargesWaivedAccountId_LedgerBalance { get; set; }
    public decimal? ChargesWaivedAccountId_AvailableBalance { get; set; }
    public bool? ChargesWaivedAccountId_IsOfficeAccount { get; set; }
    public bool? ChargesWaivedAccountId_AllowManualEntry { get; set; }
    public bool? ChargesWaivedAccountId_IsClosed { get; set; }
    public DateTime? ChargesWaivedAccountId_DateClosed { get; set; }
    public string? ChargesWaivedAccountId_ClosedByUserName { get; set; }
    public bool? ChargesWaivedAccountId_IsActive { get; set; }
    public string? ChargesWaivedAccountId_CreatedByUserId { get; set; }
    public string? ChargesWaivedAccountId_UpdatedByUserId { get; set; }
    public string? ChargesWaivedAccountId_DeletedByUserId { get; set; }
    public bool? ChargesWaivedAccountId_IsDeleted { get; set; }
    public string? ChargesWaivedAccountId_Tags { get; set; }
    public string? ChargesWaivedAccountId_Caption { get; set; }
    public string? InterestPayableAccountId_AccountType { get; set; }
    public string? InterestPayableAccountId_UOM { get; set; }
    public string? InterestPayableAccountId_CurrencyId { get; set; }
    public string? InterestPayableAccountId_Code { get; set; }
    public string? InterestPayableAccountId_Name { get; set; }
    public string? InterestPayableAccountId_ParentId { get; set; }
    public decimal? InterestPayableAccountId_ClearedBalance { get; set; }
    public decimal? InterestPayableAccountId_UnclearedBalance { get; set; }
    public decimal? InterestPayableAccountId_LedgerBalance { get; set; }
    public decimal? InterestPayableAccountId_AvailableBalance { get; set; }
    public bool? InterestPayableAccountId_IsOfficeAccount { get; set; }
    public bool? InterestPayableAccountId_AllowManualEntry { get; set; }
    public bool? InterestPayableAccountId_IsClosed { get; set; }
    public DateTime? InterestPayableAccountId_DateClosed { get; set; }
    public string? InterestPayableAccountId_ClosedByUserName { get; set; }
    public bool? InterestPayableAccountId_IsActive { get; set; }
    public string? InterestPayableAccountId_CreatedByUserId { get; set; }
    public string? InterestPayableAccountId_UpdatedByUserId { get; set; }
    public string? InterestPayableAccountId_DeletedByUserId { get; set; }
    public bool? InterestPayableAccountId_IsDeleted { get; set; }
    public string? InterestPayableAccountId_Tags { get; set; }
    public string? InterestPayableAccountId_Caption { get; set; }
    public string? InterestPayoutAccountId_AccountType { get; set; }
    public string? InterestPayoutAccountId_UOM { get; set; }
    public string? InterestPayoutAccountId_CurrencyId { get; set; }
    public string? InterestPayoutAccountId_Code { get; set; }
    public string? InterestPayoutAccountId_Name { get; set; }
    public string? InterestPayoutAccountId_ParentId { get; set; }
    public decimal? InterestPayoutAccountId_ClearedBalance { get; set; }
    public decimal? InterestPayoutAccountId_UnclearedBalance { get; set; }
    public decimal? InterestPayoutAccountId_LedgerBalance { get; set; }
    public decimal? InterestPayoutAccountId_AvailableBalance { get; set; }
    public bool? InterestPayoutAccountId_IsOfficeAccount { get; set; }
    public bool? InterestPayoutAccountId_AllowManualEntry { get; set; }
    public bool? InterestPayoutAccountId_IsClosed { get; set; }
    public DateTime? InterestPayoutAccountId_DateClosed { get; set; }
    public string? InterestPayoutAccountId_ClosedByUserName { get; set; }
    public bool? InterestPayoutAccountId_IsActive { get; set; }
    public string? InterestPayoutAccountId_CreatedByUserId { get; set; }
    public string? InterestPayoutAccountId_UpdatedByUserId { get; set; }
    public string? InterestPayoutAccountId_DeletedByUserId { get; set; }
    public bool? InterestPayoutAccountId_IsDeleted { get; set; }
    public string? InterestPayoutAccountId_Tags { get; set; }
    public string? InterestPayoutAccountId_Caption { get; set; }
}