namespace AP.ChevronCoop.Entities.Loans.LoanApplicationGuarantors;

public class LoanApplicationGuarantorMasterView
{
    public long? RowNumber { get; set; }
    public string Id { get; set; }
    public string LoanApplicationId { get; set; }
    public string GuarantorType { get; set; }
    public string GuarantorId { get; set; }
    public string Status { get; set; }
    public DateTime? ApprovedOn { get; set; }
    public string? Comment { get; set; }
    public string GuarantorApprovalType { get; set; }
    public string? Description { get; set; }
    public bool IsActive { get; set; }
    public string? CreatedByUserId { get; set; }
    public DateTimeOffset? DateCreated { get; set; }
    public string? UpdatedByUserId { get; set; }
    public DateTimeOffset? DateUpdated { get; set; }
    public string? DeletedByUserId { get; set; }
    public bool IsDeleted { get; set; }
    public DateTimeOffset? DateDeleted { get; set; }
    public Guid RowVersion { get; set; }
    public string? FullText { get; set; }
    public string? Tags { get; set; }
    public string? Caption { get; set; }
    public string? LoanApplicationId_ApplicationNo { get; set; }
    public string? LoanApplicationId_AccountNo { get; set; }
    public string? LoanApplicationId_LoanProductId { get; set; }
    public string? LoanApplicationId_ApprovalId { get; set; }
    public string? LoanApplicationId_CustomerId { get; set; }
    public decimal? LoanApplicationId_Principal { get; set; }
    public string? LoanApplicationId_TenureUnit { get; set; }
    public decimal? LoanApplicationId_TenureValue { get; set; }
    public DateTimeOffset? LoanApplicationId_RepaymentCommencementDate { get; set; }
    public bool? LoanApplicationId_UseSpecialDeposit { get; set; }
    public string? LoanApplicationId_SpecialDepositId { get; set; }
    public string? LoanApplicationId_CustomerDisbursementAccountId { get; set; }
    public string? LoanApplicationId_QualificationTargetProductId { get; set; }
    public string? LoanApplicationId_Status { get; set; }
    public string? LoanApplicationId_QualificationTargetProductType { get; set; }
    public bool? LoanApplicationId_IsActive { get; set; }
    public string? LoanApplicationId_CreatedByUserId { get; set; }
    public string? LoanApplicationId_UpdatedByUserId { get; set; }
    public string? LoanApplicationId_DeletedByUserId { get; set; }
    public bool? LoanApplicationId_IsDeleted { get; set; }
    public string? LoanApplicationId_Tags { get; set; }
    public string? LoanApplicationId_Caption { get; set; }
    public string? GuarantorId_CustomerNo { get; set; }
    public string? GuarantorId_ApplicationUserId { get; set; }
    public string? GuarantorId_CashAccountId { get; set; }
    public int? GuarantorId_YearsOfService { get; set; }
    public bool? GuarantorId_IsKycStarted { get; set; }
    public bool? GuarantorId_IsKycCompleted { get; set; }
    public DateTime? GuarantorId_KycStartDate { get; set; }
    public DateTime? GuarantorId_KycCompletedDate { get; set; }
    public string? GuarantorId_Status { get; set; }
    public string? GuarantorId_MemberType { get; set; }
    public string? GuarantorId_Gender { get; set; }
    public string? GuarantorId_ProfileImageUrl { get; set; }
    public string? GuarantorId_PassportUrl { get; set; }
    public string? GuarantorId_IdentificationType { get; set; }
    public string? GuarantorId_IdentificationNumber { get; set; }
    public string? GuarantorId_IdentificationUrl { get; set; }
    public bool? GuarantorId_KycSubmitted { get; set; }
    public DateTime? GuarantorId_KycSubmittedOn { get; set; }
    public bool? GuarantorId_KycApproved { get; set; }
    public DateTime? GuarantorId_KycApprovedOn { get; set; }
    public bool? GuarantorId_KycApprovedBy { get; set; }
    public string? GuarantorId_FirstName { get; set; }
    public string? GuarantorId_LastName { get; set; }
    public string? GuarantorId_MiddleName { get; set; }
    public string? GuarantorId_DepartmentId { get; set; }
    public string? GuarantorId_MemberId { get; set; }
    public string? GuarantorId_CAI { get; set; }
    public string? GuarantorId_RetireeNumber { get; set; }
    public string? GuarantorId_StateOfOrigin { get; set; }
    public string? GuarantorId_PrimaryEmail { get; set; }
    public string? GuarantorId_SecondaryEmail { get; set; }
    public string? GuarantorId_PrimaryPhone { get; set; }
    public string? GuarantorId_SecondaryPhone { get; set; }
    public string? GuarantorId_ResidentialAddress { get; set; }
    public string? GuarantorId_OfficeAddress { get; set; }
    public string? GuarantorId_Rank { get; set; }
    public string? GuarantorId_JobRole { get; set; }
    public DateTimeOffset? GuarantorId_DOB { get; set; }
    public string? GuarantorId_Address { get; set; }
    public string? GuarantorId_Country { get; set; }
    public string? GuarantorId_State { get; set; }
    public bool? GuarantorId_IsActive { get; set; }
    public string? GuarantorId_CreatedByUserId { get; set; }
    public string? GuarantorId_UpdatedByUserId { get; set; }
    public string? GuarantorId_DeletedByUserId { get; set; }
    public bool? GuarantorId_IsDeleted { get; set; }
    public string? GuarantorId_Tags { get; set; }
    public string? GuarantorId_Caption { get; set; }
}