namespace AP.ChevronCoop.Entities.Loans.LoanOffSetCharges;

public class LoanOffSetChargeMasterView
{
  public long? RowNumber { get; set; }
  public string Id { get; set; }
  public string LoanOffsetId { get; set; }
  public string OffsetChargeId { get; set; }
  public string ChargeType { get; set; }
  public decimal TotalCharge { get; set; }
  public string? TransactionJournalId { get; set; }
  public bool IsProcessed { get; set; }
  public DateTime? ProcessedDate { get; set; }
  public string? Description { get; set; }
  public bool IsActive { get; set; }
  public string? CreatedByUserId { get; set; }
  public DateTimeOffset? DateCreated { get; set; }
  public string? UpdatedByUserId { get; set; }
  public DateTimeOffset? DateUpdated { get; set; }
  public string? DeletedByUserId { get; set; }
  public bool IsDeleted { get; set; }
  public DateTimeOffset? DateDeleted { get; set; }
  public Guid RowVersion { get; set; }
  public string? FullText { get; set; }
  public string? Tags { get; set; }
  public string? Caption { get; set; }
  public string? LoanOffsetId_LoanAccountId { get; set; }
  public decimal? LoanOffsetId_OffsetAmount { get; set; }
  public decimal? LoanOffsetId_OldPrincipalBalance { get; set; }
  public decimal? LoanOffsetId_NewPrincipalBalance { get; set; }
  public decimal? LoanOffsetId_OldInterestBalance { get; set; }
  public decimal? LoanOffsetId_NewInterestBalance { get; set; }
  public decimal? LoanOffsetId_TotalOffsetCharges { get; set; }
  public bool? LoanOffsetId_IsLiquidated { get; set; }
  public string? LoanOffsetId_AllowedOffsetType { get; set; }
  public string? LoanOffsetId_LoanRepaymentMode { get; set; }
  public DateTimeOffset? LoanOffsetId_OffSetRepaymentDate { get; set; }
  public string? LoanOffsetId_SavingsAccountId { get; set; }
  public string? LoanOffsetId_SpecialDepositAccountId { get; set; }
  public string? LoanOffsetId_CustomerBankAccountId { get; set; }
  public int? LoanOffsetId_ModeOfPayment { get; set; }
  public string? LoanOffsetId_CustomerPaymentDocumentId { get; set; }
  public string? LoanOffsetId_TransactionJournalId { get; set; }
  public string? LoanOffsetId_ApprovalId { get; set; }
  public bool? LoanOffsetId_IsProcessed { get; set; }
  public DateTime? LoanOffsetId_ProcessedDate { get; set; }
  public string? LoanOffsetId_Status { get; set; }
  public bool? LoanOffsetId_IsActive { get; set; }
  public string? LoanOffsetId_CreatedByUserId { get; set; }
  public string? LoanOffsetId_UpdatedByUserId { get; set; }
  public string? LoanOffsetId_DeletedByUserId { get; set; }
  public bool? LoanOffsetId_IsDeleted { get; set; }
  public string? LoanOffsetId_Tags { get; set; }
  public string? LoanOffsetId_Caption { get; set; }
  public string? LoanOffsetId_RepaymentSchedules { get; set; }
  public string? OffsetChargeId_Code { get; set; }
  public string? OffsetChargeId_Name { get; set; }
  public string? OffsetChargeId_Method { get; set; }
  public string? OffsetChargeId_Target { get; set; }
  public string? OffsetChargeId_CalculationMethod { get; set; }
  public string? OffsetChargeId_CurrencyId { get; set; }
  public decimal? OffsetChargeId_ChargeValue { get; set; }
  public decimal? OffsetChargeId_MaximumCharge { get; set; }
  public decimal? OffsetChargeId_MinimimumCharge { get; set; }
  public bool? OffsetChargeId_IsActive { get; set; }
  public string? OffsetChargeId_CreatedByUserId { get; set; }
  public string? OffsetChargeId_UpdatedByUserId { get; set; }
  public string? OffsetChargeId_DeletedByUserId { get; set; }
  public bool? OffsetChargeId_IsDeleted { get; set; }
  public string? OffsetChargeId_Tags { get; set; }
  public string? OffsetChargeId_Caption { get; set; }
  public string? TransactionJournalId_TransactionNo { get; set; }
  public string? TransactionJournalId_Title { get; set; }
  public string? TransactionJournalId_TransactionType { get; set; }
  public string? TransactionJournalId_DocumentRef { get; set; }
  public string? TransactionJournalId_DocumentRefId { get; set; }
  public string? TransactionJournalId_PostingRef { get; set; }
  public string? TransactionJournalId_PostingRefId { get; set; }
  public string? TransactionJournalId_EntityRef { get; set; }
  public string? TransactionJournalId_EntityRefId { get; set; }
  public DateTime? TransactionJournalId_TransactionDate { get; set; }
  public bool? TransactionJournalId_IsPosted { get; set; }
  public string? TransactionJournalId_PostedByUserId { get; set; }
  public DateTime? TransactionJournalId_DatePosted { get; set; }
  public bool? TransactionJournalId_IsReversed { get; set; }
  public string? TransactionJournalId_ReversedByUserId { get; set; }
  public DateTime? TransactionJournalId_ReversalDate { get; set; }
  public string? TransactionJournalId_ApprovalId { get; set; }
  public DateTime? TransactionJournalId_ApprovalDate { get; set; }
  public string? TransactionJournalId_Memo { get; set; }
  public bool? TransactionJournalId_IsActive { get; set; }
  public string? TransactionJournalId_CreatedByUserId { get; set; }
  public string? TransactionJournalId_UpdatedByUserId { get; set; }
  public string? TransactionJournalId_DeletedByUserId { get; set; }
  public bool? TransactionJournalId_IsDeleted { get; set; }
  public string? TransactionJournalId_Tags { get; set; }
  public string? TransactionJournalId_Caption { get; set; }
}