namespace AP.ChevronCoop.Entities.Accounting.TransactionJournals;

public class TransactionJournalMasterView
{
    public long? RowNumber { get; set; }
    public string Id { get; set; }
    public string TransactionNo { get; set; }
    public string Title { get; set; }
    public string TransactionType { get; set; }
    public string? DocumentRef { get; set; }
    public string? DocumentRefId { get; set; }
    public string? PostingRef { get; set; }
    public string? PostingRefId { get; set; }
    public string? EntityRef { get; set; }
    public string? EntityRefId { get; set; }
    public DateTime TransactionDate { get; set; }
    public bool IsPosted { get; set; }
    public string? PostedByUserId { get; set; }
    public DateTime? DatePosted { get; set; }
    public bool IsReversed { get; set; }
    public string? ReversedByUserId { get; set; }
    public DateTime? ReversalDate { get; set; }
    public string? ApprovalId { get; set; }
    public DateTime? ApprovalDate { get; set; }
    public string? Memo { get; set; }
    public string? Description { get; set; }
    public bool IsActive { get; set; }
    public string? CreatedByUserId { get; set; }
    public DateTimeOffset? DateCreated { get; set; }
    public string? UpdatedByUserId { get; set; }
    public DateTimeOffset? DateUpdated { get; set; }
    public string? DeletedByUserId { get; set; }
    public bool IsDeleted { get; set; }
    public DateTimeOffset? DateDeleted { get; set; }
    public Guid RowVersion { get; set; }
    public string? FullText { get; set; }
    public string? Tags { get; set; }
    public string? Caption { get; set; }
    public string? PostedByUserId_AdObjectId { get; set; }
    public bool? PostedByUserId_IsAdmin { get; set; }
    public string? PostedByUserId_SecondaryPhone { get; set; }
    public bool? PostedByUserId_SecondaryPhoneConfirmed { get; set; }
    public string? PostedByUserId_UserName { get; set; }
    public string? PostedByUserId_NormalizedUserName { get; set; }
    public string? PostedByUserId_Email { get; set; }
    public string? PostedByUserId_NormalizedEmail { get; set; }
    public bool? PostedByUserId_EmailConfirmed { get; set; }
    public string? PostedByUserId_PasswordHash { get; set; }
    public string? PostedByUserId_SecurityStamp { get; set; }
    public string? PostedByUserId_ConcurrencyStamp { get; set; }
    public string? PostedByUserId_PhoneNumber { get; set; }
    public bool? PostedByUserId_PhoneNumberConfirmed { get; set; }
    public bool? PostedByUserId_TwoFactorEnabled { get; set; }
    public DateTimeOffset? PostedByUserId_LockoutEnd { get; set; }
    public bool? PostedByUserId_LockoutEnabled { get; set; }
    public int? PostedByUserId_AccessFailedCount { get; set; }
    public string? ReversedByUserId_AdObjectId { get; set; }
    public bool? ReversedByUserId_IsAdmin { get; set; }
    public string? ReversedByUserId_SecondaryPhone { get; set; }
    public bool? ReversedByUserId_SecondaryPhoneConfirmed { get; set; }
    public string? ReversedByUserId_UserName { get; set; }
    public string? ReversedByUserId_NormalizedUserName { get; set; }
    public string? ReversedByUserId_Email { get; set; }
    public string? ReversedByUserId_NormalizedEmail { get; set; }
    public bool? ReversedByUserId_EmailConfirmed { get; set; }
    public string? ReversedByUserId_PasswordHash { get; set; }
    public string? ReversedByUserId_SecurityStamp { get; set; }
    public string? ReversedByUserId_ConcurrencyStamp { get; set; }
    public string? ReversedByUserId_PhoneNumber { get; set; }
    public bool? ReversedByUserId_PhoneNumberConfirmed { get; set; }
    public bool? ReversedByUserId_TwoFactorEnabled { get; set; }
    public DateTimeOffset? ReversedByUserId_LockoutEnd { get; set; }
    public bool? ReversedByUserId_LockoutEnabled { get; set; }
    public int? ReversedByUserId_AccessFailedCount { get; set; }
    public string? ApprovalId_Module { get; set; }
    public string? ApprovalId_ApprovalType { get; set; }
    public string? ApprovalId_Status { get; set; }
    public int? ApprovalId_CurrentSequence { get; set; }
    public string? ApprovalId_ApprovalWorkflowId { get; set; }
    public string? ApprovalId_Payload { get; set; }
    public bool? ApprovalId_IsApprovalCompleted { get; set; }
    public string? ApprovalId_Comment { get; set; }
    public string? ApprovalId_EntityId { get; set; }
    public int? ApprovalId_TriedCount { get; set; }
    public bool? ApprovalId_IsActive { get; set; }
    public string? ApprovalId_CreatedByUserId { get; set; }
    public string? ApprovalId_UpdatedByUserId { get; set; }
    public string? ApprovalId_DeletedByUserId { get; set; }
    public bool? ApprovalId_IsDeleted { get; set; }
    public string? ApprovalId_Tags { get; set; }
    public string? ApprovalId_Caption { get; set; }
    public string? ApprovalId_ApprovalViewModelPayload { get; set; }
}