using System.ComponentModel.DataAnnotations.Schema;

namespace AP.ChevronCoop.Entities.Deposits.Products.DepartmentDepositProductPublications;

[Table(nameof(CustomerDepositProductPublicationMasterView), Schema = "Deposits")]
public class CustomerDepositProductPublicationMasterView
{
    public long? RowNumber { get; set; }
    public string Id { get; set; }
    public string PublicationType { get; set; }
    public string ProductId { get; set; }
    public string? CustomerId { get; set; }
    public string? Description { get; set; }
    public bool IsActive { get; set; }
    public string? CreatedByUserId { get; set; }
    public DateTimeOffset? DateCreated { get; set; }
    public string? UpdatedByUserId { get; set; }
    public DateTimeOffset? DateUpdated { get; set; }
    public string? DeletedByUserId { get; set; }
    public bool IsDeleted { get; set; }
    public DateTimeOffset? DateDeleted { get; set; }
    public Guid RowVersion { get; set; }
    public string? FullText { get; set; }
    public string? Tags { get; set; }
    public string? Caption { get; set; }
    public string? ProductId_Code { get; set; }
    public string? ProductId_Name { get; set; }
    public string? ProductId_ShortName { get; set; }
    public string? ProductId_ApprovalWorkflowId { get; set; }
    public string? ProductId_ApprovalId { get; set; }
    public int? ProductId_MinimumAge { get; set; }
    public int? ProductId_MaximumAge { get; set; }
    public string? ProductId_Tenure { get; set; }
    public decimal? ProductId_TenureValue { get; set; }
    public string? ProductId_Status { get; set; }
    public string? ProductId_PublicationType { get; set; }
    public string? ProductId_PublishedByUserId { get; set; }
    public string? ProductId_DefaultCurrencyId { get; set; }
    public string? ProductId_BankDepositAccountId { get; set; }
    public string? ProductId_ProductDepositAccountId { get; set; }
    public string? ProductId_ChargesIncomeAccountId { get; set; }
    public string? ProductId_ChargesAccrualAccountId { get; set; }
    public string? ProductId_ChargesWaivedAccountId { get; set; }
    public string? ProductId_InterestPayableAccountId { get; set; }
    public string? ProductId_InterestPayoutAccountId { get; set; }
    public bool? ProductId_IsInterestEnabled { get; set; }
    public decimal? ProductId_MinimumContributionRegular { get; set; }
    public decimal? ProductId_MinimumContributionRetiree { get; set; }
    public string? ProductId_ProductType { get; set; }
    public bool? ProductId_IsActive { get; set; }
    public string? ProductId_CreatedByUserId { get; set; }
    public string? ProductId_UpdatedByUserId { get; set; }
    public string? ProductId_DeletedByUserId { get; set; }
    public bool? ProductId_IsDeleted { get; set; }
    public string? ProductId_Tags { get; set; }
    public string? ProductId_Caption { get; set; }
    public bool? ProductId_IsDefaultProduct { get; set; }
    public string? CustomerId_CustomerNo { get; set; }
    public string? CustomerId_ApplicationUserId { get; set; }
    public string? CustomerId_CashAccountId { get; set; }
    public int? CustomerId_YearsOfService { get; set; }
    public bool? CustomerId_IsKycStarted { get; set; }
    public bool? CustomerId_IsKycCompleted { get; set; }
    public DateTime? CustomerId_KycStartDate { get; set; }
    public DateTime? CustomerId_KycCompletedDate { get; set; }
    public string? CustomerId_Status { get; set; }
    public string? CustomerId_MemberType { get; set; }
    public string? CustomerId_Gender { get; set; }
    public string? CustomerId_ProfileImageUrl { get; set; }
    public string? CustomerId_PassportUrl { get; set; }
    public string? CustomerId_IdentificationType { get; set; }
    public string? CustomerId_IdentificationNumber { get; set; }
    public string? CustomerId_IdentificationUrl { get; set; }
    public bool? CustomerId_KycSubmitted { get; set; }
    public DateTime? CustomerId_KycSubmittedOn { get; set; }
    public bool? CustomerId_KycApproved { get; set; }
    public DateTime? CustomerId_KycApprovedOn { get; set; }
    public bool? CustomerId_KycApprovedBy { get; set; }
    public string? CustomerId_FirstName { get; set; }
    public string? CustomerId_LastName { get; set; }
    public string? CustomerId_MiddleName { get; set; }
    public string? CustomerId_DepartmentId { get; set; }
    public string? CustomerId_MemberId { get; set; }
    public string? CustomerId_CAI { get; set; }
    public string? CustomerId_RetireeNumber { get; set; }
    public string? CustomerId_StateOfOrigin { get; set; }
    public string? CustomerId_PrimaryEmail { get; set; }
    public string? CustomerId_SecondaryEmail { get; set; }
    public string? CustomerId_PrimaryPhone { get; set; }
    public string? CustomerId_SecondaryPhone { get; set; }
    public string? CustomerId_ResidentialAddress { get; set; }
    public string? CustomerId_OfficeAddress { get; set; }
    public string? CustomerId_Rank { get; set; }
    public string? CustomerId_JobRole { get; set; }
    public DateTimeOffset? CustomerId_DOB { get; set; }
    public string? CustomerId_Address { get; set; }
    public string? CustomerId_Country { get; set; }
    public string? CustomerId_State { get; set; }
    public bool? CustomerId_IsActive { get; set; }
    public string? CustomerId_CreatedByUserId { get; set; }
    public string? CustomerId_UpdatedByUserId { get; set; }
    public string? CustomerId_DeletedByUserId { get; set; }
    public bool? CustomerId_IsDeleted { get; set; }
    public string? CustomerId_Tags { get; set; }
    public string? CustomerId_Caption { get; set; }
    public DateTime? CustomerId_DateOfEmployment { get; set; }
}