namespace AP.ChevronCoop.Entities.Loans.LoanDisbursements;

public class LoanDisbursementMasterView
{
  public long? RowNumber { get; set; }
  public string Id { get; set; }
  public string LoanAccountId { get; set; }
  public decimal Amount { get; set; }
  public string? ApprovedByUserId { get; set; }
  public string? DisbursedByUserId { get; set; }
  public string DisbursementStatus { get; set; }
  public string? DisbursementAccountId { get; set; }
  public DateTimeOffset? DisbursementDate { get; set; }
  public string DisbursementMode { get; set; }
  public string? SpecialDepositAccountId { get; set; }
  public string? CustomerBankAccountId { get; set; }
  public string? TransactionJournalId { get; set; }
  public string? ApprovalId { get; set; }
  public DateTimeOffset? ApprovalDate { get; set; }
  public bool IsProcessed { get; set; }
  public DateTime? ProcessedDate { get; set; }
  public string Status { get; set; }
  public string? Description { get; set; }
  public bool IsActive { get; set; }
  public string? CreatedByUserId { get; set; }
  public DateTimeOffset? DateCreated { get; set; }
  public string? UpdatedByUserId { get; set; }
  public DateTimeOffset? DateUpdated { get; set; }
  public string? DeletedByUserId { get; set; }
  public bool IsDeleted { get; set; }
  public DateTimeOffset? DateDeleted { get; set; }
  public Guid RowVersion { get; set; }
  public string? FullText { get; set; }
  public string? Tags { get; set; }
  public string? Caption { get; set; }
  public string? TransactionType { get; set; }
  public string? LoanAccountId_AccountNo { get; set; }
  public string? LoanAccountId_LoanApplicationId { get; set; }
  public string? LoanAccountId_CustomerId { get; set; }
  public string? LoanAccountId_PrincipalBalanceAccountId { get; set; }
  public string? LoanAccountId_PrincipalLossAccountId { get; set; }
  public string? LoanAccountId_EarnedInterestAccountId { get; set; }
  public string? LoanAccountId_InterestBalanceAccountId { get; set; }
  public string? LoanAccountId_UnearnedInterestAccountId { get; set; }
  public string? LoanAccountId_InterestLossAccountId { get; set; }
  public string? LoanAccountId_InterestWaivedAccountId { get; set; }
  public string? LoanAccountId_ChargesAccruedAccountId { get; set; }
  public string? LoanAccountId_ChargesIncomeAccountId { get; set; }
  public string? LoanAccountId_ChargesWaivedAccountId { get; set; }
  public decimal? LoanAccountId_Principal { get; set; }
  public string? LoanAccountId_TenureUnit { get; set; }
  public decimal? LoanAccountId_TenureValue { get; set; }
  public DateTimeOffset? LoanAccountId_RepaymentCommencementDate { get; set; }
  public bool? LoanAccountId_UseSpecialDeposit { get; set; }
  public string? LoanAccountId_SpecialDepositAccountId { get; set; }
  public string? LoanAccountId_DestinationAccountId { get; set; }
  public bool? LoanAccountId_IsClosed { get; set; }
  public DateTime? LoanAccountId_DateClosed { get; set; }
  public string? LoanAccountId_ClosedByUserId { get; set; }
  public string? LoanAccountId_LoanTopupId { get; set; }
  public string? LoanAccountId_InterestPayoutAccountId { get; set; }
  public bool? LoanAccountId_IsActive { get; set; }
  public string? LoanAccountId_CreatedByUserId { get; set; }
  public string? LoanAccountId_UpdatedByUserId { get; set; }
  public string? LoanAccountId_DeletedByUserId { get; set; }
  public bool? LoanAccountId_IsDeleted { get; set; }
  public string? LoanAccountId_Tags { get; set; }
  public string? LoanAccountId_Caption { get; set; }
  public string? LoanAccountId_LoanCreationType { get; set; }
  public string? LoanAccountId_ParentAccountId { get; set; }
  public string? LoanAccountId_RootParentAccountId { get; set; }
  public string? ApprovedByUserId_AdObjectId { get; set; }
  public bool? ApprovedByUserId_IsAdmin { get; set; }
  public string? ApprovedByUserId_SecondaryPhone { get; set; }
  public bool? ApprovedByUserId_SecondaryPhoneConfirmed { get; set; }
  public string? ApprovedByUserId_UserName { get; set; }
  public string? ApprovedByUserId_NormalizedUserName { get; set; }
  public string? ApprovedByUserId_Email { get; set; }
  public string? ApprovedByUserId_NormalizedEmail { get; set; }
  public bool? ApprovedByUserId_EmailConfirmed { get; set; }
  public string? ApprovedByUserId_PasswordHash { get; set; }
  public string? ApprovedByUserId_SecurityStamp { get; set; }
  public string? ApprovedByUserId_ConcurrencyStamp { get; set; }
  public string? ApprovedByUserId_PhoneNumber { get; set; }
  public bool? ApprovedByUserId_PhoneNumberConfirmed { get; set; }
  public bool? ApprovedByUserId_TwoFactorEnabled { get; set; }
  public DateTimeOffset? ApprovedByUserId_LockoutEnd { get; set; }
  public bool? ApprovedByUserId_LockoutEnabled { get; set; }
  public int? ApprovedByUserId_AccessFailedCount { get; set; }
  public string? DisbursedByUserId_AdObjectId { get; set; }
  public bool? DisbursedByUserId_IsAdmin { get; set; }
  public string? DisbursedByUserId_SecondaryPhone { get; set; }
  public bool? DisbursedByUserId_SecondaryPhoneConfirmed { get; set; }
  public string? DisbursedByUserId_UserName { get; set; }
  public string? DisbursedByUserId_NormalizedUserName { get; set; }
  public string? DisbursedByUserId_Email { get; set; }
  public string? DisbursedByUserId_NormalizedEmail { get; set; }
  public bool? DisbursedByUserId_EmailConfirmed { get; set; }
  public string? DisbursedByUserId_PasswordHash { get; set; }
  public string? DisbursedByUserId_SecurityStamp { get; set; }
  public string? DisbursedByUserId_ConcurrencyStamp { get; set; }
  public string? DisbursedByUserId_PhoneNumber { get; set; }
  public bool? DisbursedByUserId_PhoneNumberConfirmed { get; set; }
  public bool? DisbursedByUserId_TwoFactorEnabled { get; set; }
  public DateTimeOffset? DisbursedByUserId_LockoutEnd { get; set; }
  public bool? DisbursedByUserId_LockoutEnabled { get; set; }
  public int? DisbursedByUserId_AccessFailedCount { get; set; }
  public string? DisbursementAccountId_LedgerAccountId { get; set; }
  public string? DisbursementAccountId_BankId { get; set; }
  public string? DisbursementAccountId_BranchName { get; set; }
  public string? DisbursementAccountId_BranchAddress { get; set; }
  public string? DisbursementAccountId_CurrencyId { get; set; }
  public string? DisbursementAccountId_AccountName { get; set; }
  public string? DisbursementAccountId_AccountNumber { get; set; }
  public string? DisbursementAccountId_BVN { get; set; }
  public bool? DisbursementAccountId_IsActive { get; set; }
  public string? DisbursementAccountId_CreatedByUserId { get; set; }
  public string? DisbursementAccountId_UpdatedByUserId { get; set; }
  public string? DisbursementAccountId_DeletedByUserId { get; set; }
  public bool? DisbursementAccountId_IsDeleted { get; set; }
  public string? DisbursementAccountId_Tags { get; set; }
  public string? DisbursementAccountId_Caption { get; set; }
  public string? SpecialDepositAccountId_ApplicationId { get; set; }
  public string? SpecialDepositAccountId_AccountNo { get; set; }
  public string? SpecialDepositAccountId_CustomerId { get; set; }
  public string? SpecialDepositAccountId_DepositProductId { get; set; }
  public string? SpecialDepositAccountId_DepositAccountId { get; set; }
  public string? SpecialDepositAccountId_ChargesAccruedAccountId { get; set; }
  public string? SpecialDepositAccountId_ChargesIncomeAccountId { get; set; }
  public string? SpecialDepositAccountId_ChargesWaivedAccountId { get; set; }
  public string? SpecialDepositAccountId_InterestEarnedAccountId { get; set; }
  public string? SpecialDepositAccountId_InterestPayoutAccountId { get; set; }
  public decimal? SpecialDepositAccountId_FundingAmount { get; set; }
  public decimal? SpecialDepositAccountId_InterestRate { get; set; }
  public DateTime? SpecialDepositAccountId_LastInterestComputationDate { get; set; }
  public decimal? SpecialDepositAccountId_MaximumBalanceLimit { get; set; }
  public decimal? SpecialDepositAccountId_MinimumBalanceLimit { get; set; }
  public decimal? SpecialDepositAccountId_SingleWithdrawalLimit { get; set; }
  public decimal? SpecialDepositAccountId_DailyWithdrawalLimit { get; set; }
  public decimal? SpecialDepositAccountId_WeeklyWithdrawalLimit { get; set; }
  public decimal? SpecialDepositAccountId_MonthlyWithdrawalLimit { get; set; }
  public bool? SpecialDepositAccountId_IsClosed { get; set; }
  public DateTime? SpecialDepositAccountId_DateClosed { get; set; }
  public string? SpecialDepositAccountId_ClosedByUserId { get; set; }
  public bool? SpecialDepositAccountId_IsActive { get; set; }
  public string? SpecialDepositAccountId_CreatedByUserId { get; set; }
  public string? SpecialDepositAccountId_UpdatedByUserId { get; set; }
  public string? SpecialDepositAccountId_DeletedByUserId { get; set; }
  public bool? SpecialDepositAccountId_IsDeleted { get; set; }
  public string? SpecialDepositAccountId_Tags { get; set; }
  public string? SpecialDepositAccountId_Caption { get; set; }
  public string? CustomerBankAccountId_LedgerAccountId { get; set; }
  public string? CustomerBankAccountId_CustomerId { get; set; }
  public string? CustomerBankAccountId_BankId { get; set; }
  public string? CustomerBankAccountId_AccountName { get; set; }
  public string? CustomerBankAccountId_AccountNumber { get; set; }
  public string? CustomerBankAccountId_BVN { get; set; }
  public string? CustomerBankAccountId_Branch { get; set; }
  public bool? CustomerBankAccountId_IsActive { get; set; }
  public string? CustomerBankAccountId_CreatedByUserId { get; set; }
  public string? CustomerBankAccountId_UpdatedByUserId { get; set; }
  public string? CustomerBankAccountId_DeletedByUserId { get; set; }
  public bool? CustomerBankAccountId_IsDeleted { get; set; }
  public string? CustomerBankAccountId_Tags { get; set; }
  public string? CustomerBankAccountId_Caption { get; set; }
  public string? TransactionJournalId_TransactionNo { get; set; }
  public string? TransactionJournalId_Title { get; set; }
  public string? TransactionJournalId_TransactionType { get; set; }
  public string? TransactionJournalId_DocumentRef { get; set; }
  public string? TransactionJournalId_DocumentRefId { get; set; }
  public string? TransactionJournalId_PostingRef { get; set; }
  public string? TransactionJournalId_PostingRefId { get; set; }
  public string? TransactionJournalId_EntityRef { get; set; }
  public string? TransactionJournalId_EntityRefId { get; set; }
  public DateTime? TransactionJournalId_TransactionDate { get; set; }
  public bool? TransactionJournalId_IsPosted { get; set; }
  public string? TransactionJournalId_PostedByUserId { get; set; }
  public DateTime? TransactionJournalId_DatePosted { get; set; }
  public bool? TransactionJournalId_IsReversed { get; set; }
  public string? TransactionJournalId_ReversedByUserId { get; set; }
  public DateTime? TransactionJournalId_ReversalDate { get; set; }
  public string? TransactionJournalId_ApprovalId { get; set; }
  public DateTime? TransactionJournalId_ApprovalDate { get; set; }
  public string? TransactionJournalId_Memo { get; set; }
  public bool? TransactionJournalId_IsActive { get; set; }
  public string? TransactionJournalId_CreatedByUserId { get; set; }
  public string? TransactionJournalId_UpdatedByUserId { get; set; }
  public string? TransactionJournalId_DeletedByUserId { get; set; }
  public bool? TransactionJournalId_IsDeleted { get; set; }
  public string? TransactionJournalId_Tags { get; set; }
  public string? TransactionJournalId_Caption { get; set; }
  public string? ApprovalId_Module { get; set; }
  public string? ApprovalId_ApprovalType { get; set; }
  public string? ApprovalId_Status { get; set; }
  public int? ApprovalId_CurrentSequence { get; set; }
  public string? ApprovalId_ApprovalWorkflowId { get; set; }
  public string? ApprovalId_Payload { get; set; }
  public bool? ApprovalId_IsApprovalCompleted { get; set; }
  public string? ApprovalId_Comment { get; set; }
  public string? ApprovalId_EntityId { get; set; }
  public int? ApprovalId_TriedCount { get; set; }
  public bool? ApprovalId_IsActive { get; set; }
  public string? ApprovalId_CreatedByUserId { get; set; }
  public string? ApprovalId_UpdatedByUserId { get; set; }
  public string? ApprovalId_DeletedByUserId { get; set; }
  public bool? ApprovalId_IsDeleted { get; set; }
  public string? ApprovalId_Tags { get; set; }
  public string? ApprovalId_Caption { get; set; }
  public string? ApprovalId_ApprovalViewModelPayload { get; set; }
}