namespace AP.ChevronCoop.Infrastructure.Services.Notification.Email.Templates;

public enum EmailTemplateType
{
    ENROLLMENT,
    GUARANTOR_APPROVAL,
    APPROVAL_NOTIFICATION,
    APPROVAL_REJECTION_NOTIFICATION,
    LOAN_APPROVAL,
    PRIVILEDGE_APPROVAL,
    FORGOT_PASSWORD,
    CREATE_APPLICATION_USER,
    LOAN_PRODUCT_INITIATION,
    DEPOSIT_APPLICATION_APPROVAL,
    DEPOSITWORKFLOW_APPROVAL,
    DEPOSIT_ACTION,
    PENDING_PAYROLL_PAYMENT,
}

