namespace AP.ChevronCoop.Entities.Deposits.Savings.SavingsIncreaseDecreases;

public class SavingsIncreaseDecreaseMasterView
{
    public long? RowNumber { get; set; }
    public string Id { get; set; }
    public string? SavingsAccountId { get; set; }
    public decimal Amount { get; set; }
    public string ContributionChangeRequest { get; set; }
    public string? ApprovalId { get; set; }
    public string? Description { get; set; }
    public bool IsActive { get; set; }
    public string? CreatedByUserId { get; set; }
    public DateTimeOffset? DateCreated { get; set; }
    public string? UpdatedByUserId { get; set; }
    public DateTimeOffset? DateUpdated { get; set; }
    public string? DeletedByUserId { get; set; }
    public bool IsDeleted { get; set; }
    public DateTimeOffset? DateDeleted { get; set; }
    public Guid RowVersion { get; set; }
    public string? FullText { get; set; }
    public string? Tags { get; set; }
    public string? Caption { get; set; }
    public string? SavingsAccountId_ApplicationId { get; set; }
    public string? SavingsAccountId_AccountNo { get; set; }
    public string? SavingsAccountId_CustomerId { get; set; }
    public string? SavingsAccountId_DepositProductId { get; set; }
    public string? SavingsAccountId_LedgerDepositAccountId { get; set; }
    public string? SavingsAccountId_ChargesPayableAccountId { get; set; }
    public string? SavingsAccountId_ChargesAccruedAccountId { get; set; }
    public string? SavingsAccountId_ChargesWaivedAccountId { get; set; }
    public string? SavingsAccountId_ChargesIncomeAccountId { get; set; }
    public decimal? SavingsAccountId_PayrollAmount { get; set; }
    public bool? SavingsAccountId_IsClosed { get; set; }
    public DateTime? SavingsAccountId_DateClosed { get; set; }
    public string? SavingsAccountId_ClosedByUserId { get; set; }
    public decimal? SavingsAccountId_MaximumBalanceLimit { get; set; }
    public decimal? SavingsAccountId_MinimumBalanceLimit { get; set; }
    public decimal? SavingsAccountId_SingleWithdrawalLimit { get; set; }
    public decimal? SavingsAccountId_DailyWithdrawalLimit { get; set; }
    public decimal? SavingsAccountId_WeeklyWithdrawalLimit { get; set; }
    public decimal? SavingsAccountId_MonthlyWithdrawalLimit { get; set; }
    public bool? SavingsAccountId_IsActive { get; set; }
    public string? SavingsAccountId_CreatedByUserId { get; set; }
    public string? SavingsAccountId_UpdatedByUserId { get; set; }
    public string? SavingsAccountId_DeletedByUserId { get; set; }
    public bool? SavingsAccountId_IsDeleted { get; set; }
    public string? SavingsAccountId_Tags { get; set; }
    public string? SavingsAccountId_Caption { get; set; }
    public string? ApprovalId_Module { get; set; }
    public string? ApprovalId_ApprovalType { get; set; }
    public string? ApprovalId_Status { get; set; }
    public int? ApprovalId_CurrentSequence { get; set; }
    public string? ApprovalId_ApprovalWorkflowId { get; set; }
    public string? ApprovalId_Payload { get; set; }
    public bool? ApprovalId_IsApprovalCompleted { get; set; }
    public string? ApprovalId_Comment { get; set; }
    public string? ApprovalId_EntityId { get; set; }
    public int? ApprovalId_TriedCount { get; set; }
    public bool? ApprovalId_IsActive { get; set; }
    public string? ApprovalId_CreatedByUserId { get; set; }
    public string? ApprovalId_UpdatedByUserId { get; set; }
    public string? ApprovalId_DeletedByUserId { get; set; }
    public bool? ApprovalId_IsDeleted { get; set; }
    public string? ApprovalId_Tags { get; set; }
    public string? ApprovalId_Caption { get; set; }
    public string? ApprovalId_ApprovalViewModelPayload { get; set; }
}
