using System.Text.Json.Serialization;

namespace AP.ChevronCoop.Commons
{
    [Serializable]
    //[JsonObject(IsReference = false)]
    public class CommandResult<T> //: ProblemDetails
    {

        public CommandResult()
        {
            StatusCode = 200;// StatusCodes.Status200OK;
            ErrorFlag = false;
        }

        [JsonPropertyName("response")]
        //[JsonProperty("response")]
        public T Response { get; set; }

        [JsonPropertyName("errorFlag")]
        //[JsonProperty("errorFlag")]
        public bool ErrorFlag { get; set; }


        [JsonPropertyName("type")]
        public string Type { get; set; }

        //
        // Summary:
        //     A short, human-readable summary of the problem type.It SHOULD NOT change from
        //     occurrence to occurrence of the problem, except for purposes of localization(e.g.,
        //     using proactive content negotiation; see[RFC7231], Section 3.4).
        [JsonPropertyName("message")]
        public string Message { get; set; }

        //
        // Summary:
        //     The HTTP status code([RFC7231], Section 6) generated by the origin server for
        //     this occurrence of the problem.
        [JsonPropertyName("statusCode")]
        public int? StatusCode { get; set; }

        //
        // Summary:
        //     A human-readable explanation specific to this occurrence of the problem.
        [JsonPropertyName("detail")]
        public string Detail { get; set; }

        //
        // Summary:
        //     A URI reference that identifies the specific occurrence of the problem.It may
        //     or may not yield further information if dereferenced.
        [JsonPropertyName("instance")]
        public string Instance { get; set; }




        [JsonPropertyName("validationErrors")]
        //[JsonProperty("validationErrors", IsReference = false)]
        public List<ModelValidationError> ValidationErrors { get; set; }
    }
}