namespace AP.ChevronCoop.Entities.Accounting.LedgerAccounts;

public class LedgerAccountMasterView
{
    public long? RowNumber { get; set; }
    public string Id { get; set; }
    public string AccountType { get; set; }
    public string UOM { get; set; }
    public string CurrencyId { get; set; }
    public string Code { get; set; }
    public string Name { get; set; }
    public string? ParentId { get; set; }
    public decimal ClearedBalance { get; set; }
    public decimal UnclearedBalance { get; set; }
    public decimal LedgerBalance { get; set; }
    public decimal AvailableBalance { get; set; }
    public bool IsOfficeAccount { get; set; }
    public bool AllowManualEntry { get; set; }
    public bool IsClosed { get; set; }
    public DateTime? DateClosed { get; set; }
    public string? ClosedByUserName { get; set; }
    public string? Description { get; set; }
    public bool IsActive { get; set; }
    public string? CreatedByUserId { get; set; }
    public DateTimeOffset? DateCreated { get; set; }
    public string? UpdatedByUserId { get; set; }
    public DateTimeOffset? DateUpdated { get; set; }
    public string? DeletedByUserId { get; set; }
    public bool IsDeleted { get; set; }
    public DateTimeOffset? DateDeleted { get; set; }
    public Guid RowVersion { get; set; }
    public string? FullText { get; set; }
    public string? Tags { get; set; }
    public string? Caption { get; set; }
    public string? CurrencyId_Code { get; set; }
    public string? CurrencyId_Name { get; set; }
    public string? CurrencyId_Symbol { get; set; }
    public string? CurrencyId_IsoSymbol { get; set; }
    public int? CurrencyId_DecimalPlaces { get; set; }
    public string? CurrencyId_Format { get; set; }
    public bool? CurrencyId_IsActive { get; set; }
    public string? CurrencyId_CreatedByUserId { get; set; }
    public string? CurrencyId_UpdatedByUserId { get; set; }
    public string? CurrencyId_DeletedByUserId { get; set; }
    public bool? CurrencyId_IsDeleted { get; set; }
    public string? CurrencyId_Tags { get; set; }
    public string? CurrencyId_Caption { get; set; }
    public string? Header_AccountType { get; set; }
    public string? Header_UOM { get; set; }
    public string? Header_CurrencyId { get; set; }
    public string? Header_Code { get; set; }
    public string? Header_Name { get; set; }
    public string? Header_ParentId { get; set; }
    public decimal? Header_ClearedBalance { get; set; }
    public decimal? Header_UnclearedBalance { get; set; }
    public decimal? Header_LedgerBalance { get; set; }
    public decimal? Header_AvailableBalance { get; set; }
    public bool? Header_IsOfficeAccount { get; set; }
    public bool? Header_AllowManualEntry { get; set; }
    public bool? Header_IsClosed { get; set; }
    public DateTime? Header_DateClosed { get; set; }
    public string? Header_ClosedByUserName { get; set; }
    public bool? Header_IsActive { get; set; }
    public string? Header_CreatedByUserId { get; set; }
    public string? Header_UpdatedByUserId { get; set; }
    public string? Header_DeletedByUserId { get; set; }
    public bool? Header_IsDeleted { get; set; }
    public string? Header_Tags { get; set; }
    public string? Header_Caption { get; set; }
    public int? ChildCount { get; set; }
    public bool? HasChildren { get; set; }
}