namespace AP.ChevronCoop.Entities.Payroll.PayrollDeductionSchedules;

public class PayrollDeductionScheduleMasterView
{
  public long? RowNumber { get; set; }
  public string Id { get; set; }
  public string ScheduleName { get; set; }
  public string ScheduleType { get; set; }
  public string? BankAccountId { get; set; }
  public string? SpecialDepositBankAccountId { get; set; }
  public string? FixedDepositBankAccountId { get; set; }
  public int DeductionsCount { get; set; }
  public decimal TotalDeductions { get; set; }
  public int MinDecimalPlace { get; set; }
  public int MaxDecimalPlace { get; set; }
  public DateTime AdviseDate { get; set; }
  public DateTime ExpectedDate { get; set; }
  public bool IsPosted { get; set; }
  public DateTime PayrollDate { get; set; }
  public bool IsUploaded { get; set; }
  public DateTime LastUploadedDate { get; set; }
  public bool IsProcessed { get; set; }
  public DateTime ProcessedDate { get; set; }
  public int GenerateDeductionCronJobStatus { get; set; }
  public DateTime? GenerateDeductionCronJobStartedDate { get; set; }
  public DateTime? GenerateDeductionCronJobCompletedDate { get; set; }
  public int ProcessDeductionCronJobStatus { get; set; }
  public DateTime? ProcessDeductionCronJobStartedDate { get; set; }
  public DateTime? ProcessDeductionCronJobCompletedDate { get; set; }
  public string? Description { get; set; }
  public bool IsActive { get; set; }
  public string? CreatedByUserId { get; set; }
  public DateTimeOffset? DateCreated { get; set; }
  public string? UpdatedByUserId { get; set; }
  public DateTimeOffset? DateUpdated { get; set; }
  public string? DeletedByUserId { get; set; }
  public bool IsDeleted { get; set; }
  public DateTimeOffset? DateDeleted { get; set; }
  public Guid RowVersion { get; set; }
  public string? FullText { get; set; }
  public string? Tags { get; set; }
  public string? Caption { get; set; }
  public string? BankAccountId_LedgerAccountId { get; set; }
  public string? BankAccountId_BankId { get; set; }
  public string? BankAccountId_BranchName { get; set; }
  public string? BankAccountId_BranchAddress { get; set; }
  public string? BankAccountId_CurrencyId { get; set; }
  public string? BankAccountId_AccountName { get; set; }
  public string? BankAccountId_AccountNumber { get; set; }
  public string? BankAccountId_BVN { get; set; }
  public bool? BankAccountId_IsActive { get; set; }
  public string? BankAccountId_CreatedByUserId { get; set; }
  public string? BankAccountId_UpdatedByUserId { get; set; }
  public string? BankAccountId_DeletedByUserId { get; set; }
  public bool? BankAccountId_IsDeleted { get; set; }
  public string? BankAccountId_Tags { get; set; }
  public string? BankAccountId_Caption { get; set; }
  public string? SpecialDepositBankAccountId_LedgerAccountId { get; set; }
  public string? SpecialDepositBankAccountId_BankId { get; set; }
  public string? SpecialDepositBankAccountId_BranchName { get; set; }
  public string? SpecialDepositBankAccountId_BranchAddress { get; set; }
  public string? SpecialDepositBankAccountId_CurrencyId { get; set; }
  public string? SpecialDepositBankAccountId_AccountName { get; set; }
  public string? SpecialDepositBankAccountId_AccountNumber { get; set; }
  public string? SpecialDepositBankAccountId_BVN { get; set; }
  public bool? SpecialDepositBankAccountId_IsActive { get; set; }
  public string? SpecialDepositBankAccountId_CreatedByUserId { get; set; }
  public string? SpecialDepositBankAccountId_UpdatedByUserId { get; set; }
  public string? SpecialDepositBankAccountId_DeletedByUserId { get; set; }
  public bool? SpecialDepositBankAccountId_IsDeleted { get; set; }
  public string? SpecialDepositBankAccountId_Tags { get; set; }
  public string? SpecialDepositBankAccountId_Caption { get; set; }
  public string? FixedDepositBankAccountId_LedgerAccountId { get; set; }
  public string? FixedDepositBankAccountId_BankId { get; set; }
  public string? FixedDepositBankAccountId_BranchName { get; set; }
  public string? FixedDepositBankAccountId_BranchAddress { get; set; }
  public string? FixedDepositBankAccountId_CurrencyId { get; set; }
  public string? FixedDepositBankAccountId_AccountName { get; set; }
  public string? FixedDepositBankAccountId_AccountNumber { get; set; }
  public string? FixedDepositBankAccountId_BVN { get; set; }
  public bool? FixedDepositBankAccountId_IsActive { get; set; }
  public string? FixedDepositBankAccountId_CreatedByUserId { get; set; }
  public string? FixedDepositBankAccountId_UpdatedByUserId { get; set; }
  public string? FixedDepositBankAccountId_DeletedByUserId { get; set; }
  public bool? FixedDepositBankAccountId_IsDeleted { get; set; }
  public string? FixedDepositBankAccountId_Tags { get; set; }
  public string? FixedDepositBankAccountId_Caption { get; set; }
}
