namespace AP.ChevronCoop.Entities.Deposits.Savings.SavingsAccountApplications;

public class SavingsAccountApplicationMasterView
{
    public long? RowNumber { get; set; }
    public string Id { get; set; }
    public string ApplicationNo { get; set; }
    public string CustomerId { get; set; }
    public string DepositProductId { get; set; }
    public string? ApprovalId { get; set; }
    public decimal Amount { get; set; }
    public string? Description { get; set; }
    public bool IsActive { get; set; }
    public string? CreatedByUserId { get; set; }
    public DateTimeOffset? DateCreated { get; set; }
    public string? UpdatedByUserId { get; set; }
    public DateTimeOffset? DateUpdated { get; set; }
    public string? DeletedByUserId { get; set; }
    public bool IsDeleted { get; set; }
    public DateTimeOffset? DateDeleted { get; set; }
    public Guid RowVersion { get; set; }
    public string? FullText { get; set; }
    public string? Tags { get; set; }
    public string? Caption { get; set; }
    public string? CustomerId_CustomerNo { get; set; }
    public string? CustomerId_ApplicationUserId { get; set; }
    public string? CustomerId_CashAccountId { get; set; }
    public int? CustomerId_YearsOfService { get; set; }
    public bool? CustomerId_IsKycStarted { get; set; }
    public bool? CustomerId_IsKycCompleted { get; set; }
    public DateTime? CustomerId_KycStartDate { get; set; }
    public DateTime? CustomerId_KycCompletedDate { get; set; }
    public string? CustomerId_Status { get; set; }
    public string? CustomerId_MemberType { get; set; }
    public string? CustomerId_Gender { get; set; }
    public string? CustomerId_ProfileImageUrl { get; set; }
    public string? CustomerId_PassportUrl { get; set; }
    public string? CustomerId_IdentificationType { get; set; }
    public string? CustomerId_IdentificationNumber { get; set; }
    public string? CustomerId_IdentificationUrl { get; set; }
    public bool? CustomerId_KycSubmitted { get; set; }
    public DateTime? CustomerId_KycSubmittedOn { get; set; }
    public bool? CustomerId_KycApproved { get; set; }
    public DateTime? CustomerId_KycApprovedOn { get; set; }
    public bool? CustomerId_KycApprovedBy { get; set; }
    public string? CustomerId_FirstName { get; set; }
    public string? CustomerId_LastName { get; set; }
    public string? CustomerId_MiddleName { get; set; }
    public string? CustomerId_DepartmentId { get; set; }
    public string? CustomerId_MemberId { get; set; }
    public string? CustomerId_CAI { get; set; }
    public string? CustomerId_RetireeNumber { get; set; }
    public string? CustomerId_StateOfOrigin { get; set; }
    public string? CustomerId_PrimaryEmail { get; set; }
    public string? CustomerId_SecondaryEmail { get; set; }
    public string? CustomerId_PrimaryPhone { get; set; }
    public string? CustomerId_SecondaryPhone { get; set; }
    public string? CustomerId_ResidentialAddress { get; set; }
    public string? CustomerId_OfficeAddress { get; set; }
    public string? CustomerId_Rank { get; set; }
    public string? CustomerId_JobRole { get; set; }
    public DateTimeOffset? CustomerId_DOB { get; set; }
    public string? CustomerId_Address { get; set; }
    public string? CustomerId_Country { get; set; }
    public string? CustomerId_State { get; set; }
    public bool? CustomerId_IsActive { get; set; }
    public string? CustomerId_CreatedByUserId { get; set; }
    public string? CustomerId_UpdatedByUserId { get; set; }
    public string? CustomerId_DeletedByUserId { get; set; }
    public bool? CustomerId_IsDeleted { get; set; }
    public string? CustomerId_Tags { get; set; }
    public string? CustomerId_Caption { get; set; }
    public DateTime? CustomerId_DateOfEmployment { get; set; }
    public string? DepositProductId_Code { get; set; }
    public string? DepositProductId_Name { get; set; }
    public string? DepositProductId_ShortName { get; set; }
    public string? DepositProductId_ApprovalWorkflowId { get; set; }
    public string? DepositProductId_ApprovalId { get; set; }
    public int? DepositProductId_MinimumAge { get; set; }
    public int? DepositProductId_MaximumAge { get; set; }
    public string? DepositProductId_Tenure { get; set; }
    public decimal? DepositProductId_TenureValue { get; set; }
    public string? DepositProductId_Status { get; set; }
    public string? DepositProductId_PublicationType { get; set; }
    public string? DepositProductId_PublishedByUserId { get; set; }
    public string? DepositProductId_DefaultCurrencyId { get; set; }
    public string? DepositProductId_BankDepositAccountId { get; set; }
    public string? DepositProductId_ProductDepositAccountId { get; set; }
    public string? DepositProductId_ChargesIncomeAccountId { get; set; }
    public string? DepositProductId_ChargesAccrualAccountId { get; set; }
    public string? DepositProductId_ChargesWaivedAccountId { get; set; }
    public string? DepositProductId_InterestPayableAccountId { get; set; }
    public string? DepositProductId_InterestPayoutAccountId { get; set; }
    public bool? DepositProductId_IsInterestEnabled { get; set; }
    public decimal? DepositProductId_MinimumContributionRegular { get; set; }
    public decimal? DepositProductId_MinimumContributionRetiree { get; set; }
    public string? DepositProductId_ProductType { get; set; }
    public bool? DepositProductId_IsActive { get; set; }
    public string? DepositProductId_CreatedByUserId { get; set; }
    public string? DepositProductId_UpdatedByUserId { get; set; }
    public string? DepositProductId_DeletedByUserId { get; set; }
    public bool? DepositProductId_IsDeleted { get; set; }
    public string? DepositProductId_Tags { get; set; }
    public string? DepositProductId_Caption { get; set; }
    public bool? DepositProductId_IsDefaultProduct { get; set; }
    public string? ApprovalId_Module { get; set; }
    public string? ApprovalId_ApprovalType { get; set; }
    public string? ApprovalId_Status { get; set; }
    public int? ApprovalId_CurrentSequence { get; set; }
    public string? ApprovalId_ApprovalWorkflowId { get; set; }
    public string? ApprovalId_Payload { get; set; }
    public bool? ApprovalId_IsApprovalCompleted { get; set; }
    public string? ApprovalId_Comment { get; set; }
    public string? ApprovalId_EntityId { get; set; }
    public int? ApprovalId_TriedCount { get; set; }
    public bool? ApprovalId_IsActive { get; set; }
    public string? ApprovalId_CreatedByUserId { get; set; }
    public string? ApprovalId_UpdatedByUserId { get; set; }
    public string? ApprovalId_DeletedByUserId { get; set; }
    public bool? ApprovalId_IsDeleted { get; set; }
    public string? ApprovalId_Tags { get; set; }
    public string? ApprovalId_Caption { get; set; }
    public string? ApprovalId_ApprovalViewModelPayload { get; set; }
}