namespace AP.ChevronCoop.Entities.Loans.LoanTopupCharges;

public class LoanTopupChargeMasterView
{
  public long? RowNumber { get; set; }
  public string Id { get; set; }
  public string LoanTopupId { get; set; }
  public string TopupChargeId { get; set; }
  public string ChargeType { get; set; }
  public decimal TotalCharge { get; set; }
  public string? TransactionJournalId { get; set; }
  public string? Description { get; set; }
  public bool IsActive { get; set; }
  public string? CreatedByUserId { get; set; }
  public DateTimeOffset? DateCreated { get; set; }
  public string? UpdatedByUserId { get; set; }
  public DateTimeOffset? DateUpdated { get; set; }
  public string? DeletedByUserId { get; set; }
  public bool IsDeleted { get; set; }
  public DateTimeOffset? DateDeleted { get; set; }
  public Guid RowVersion { get; set; }
  public string? FullText { get; set; }
  public string? Tags { get; set; }
  public string? Caption { get; set; }
  public string? LoanTopupId_LoanAccountId { get; set; }
  public decimal? LoanTopupId_TopupAmount { get; set; }
  public string? LoanTopupId_DestinationType { get; set; }
  public string? LoanTopupId_SpecialDepositAccountId { get; set; }
  public string? LoanTopupId_CustomerBankAccountId { get; set; }
  public decimal? LoanTopupId_OldPrincipalBalance { get; set; }
  public decimal? LoanTopupId_NewPrincipalBalance { get; set; }
  public decimal? LoanTopupId_OldInterestBalance { get; set; }
  public decimal? LoanTopupId_NewInterestBalance { get; set; }
  public decimal? LoanTopupId_TotalTopupCharges { get; set; }
  public DateTimeOffset? LoanTopupId_TopupDate { get; set; }
  public DateTimeOffset? LoanTopupId_CommencementDate { get; set; }
  public string? LoanTopupId_TransactionJournalId { get; set; }
  public string? LoanTopupId_ApprovalId { get; set; }
  public bool? LoanTopupId_IsProcessed { get; set; }
  public DateTime? LoanTopupId_ProcessedDate { get; set; }
  public string? LoanTopupId_Status { get; set; }
  public bool? LoanTopupId_IsActive { get; set; }
  public string? LoanTopupId_CreatedByUserId { get; set; }
  public string? LoanTopupId_UpdatedByUserId { get; set; }
  public string? LoanTopupId_DeletedByUserId { get; set; }
  public bool? LoanTopupId_IsDeleted { get; set; }
  public string? LoanTopupId_Tags { get; set; }
  public string? LoanTopupId_Caption { get; set; }
  public string? TopupChargeId_Code { get; set; }
  public string? TopupChargeId_Name { get; set; }
  public string? TopupChargeId_Method { get; set; }
  public string? TopupChargeId_Target { get; set; }
  public string? TopupChargeId_CalculationMethod { get; set; }
  public string? TopupChargeId_CurrencyId { get; set; }
  public decimal? TopupChargeId_ChargeValue { get; set; }
  public decimal? TopupChargeId_MaximumCharge { get; set; }
  public decimal? TopupChargeId_MinimimumCharge { get; set; }
  public bool? TopupChargeId_IsActive { get; set; }
  public string? TopupChargeId_CreatedByUserId { get; set; }
  public string? TopupChargeId_UpdatedByUserId { get; set; }
  public string? TopupChargeId_DeletedByUserId { get; set; }
  public bool? TopupChargeId_IsDeleted { get; set; }
  public string? TopupChargeId_Tags { get; set; }
  public string? TopupChargeId_Caption { get; set; }
  public string? TransactionJournalId_TransactionNo { get; set; }
  public string? TransactionJournalId_Title { get; set; }
  public string? TransactionJournalId_TransactionType { get; set; }
  public string? TransactionJournalId_DocumentRef { get; set; }
  public string? TransactionJournalId_DocumentRefId { get; set; }
  public string? TransactionJournalId_PostingRef { get; set; }
  public string? TransactionJournalId_PostingRefId { get; set; }
  public string? TransactionJournalId_EntityRef { get; set; }
  public string? TransactionJournalId_EntityRefId { get; set; }
  public DateTime? TransactionJournalId_TransactionDate { get; set; }
  public bool? TransactionJournalId_IsPosted { get; set; }
  public string? TransactionJournalId_PostedByUserId { get; set; }
  public DateTime? TransactionJournalId_DatePosted { get; set; }
  public bool? TransactionJournalId_IsReversed { get; set; }
  public string? TransactionJournalId_ReversedByUserId { get; set; }
  public DateTime? TransactionJournalId_ReversalDate { get; set; }
  public string? TransactionJournalId_ApprovalId { get; set; }
  public DateTime? TransactionJournalId_ApprovalDate { get; set; }
  public string? TransactionJournalId_Memo { get; set; }
  public bool? TransactionJournalId_IsActive { get; set; }
  public string? TransactionJournalId_CreatedByUserId { get; set; }
  public string? TransactionJournalId_UpdatedByUserId { get; set; }
  public string? TransactionJournalId_DeletedByUserId { get; set; }
  public bool? TransactionJournalId_IsDeleted { get; set; }
  public string? TransactionJournalId_Tags { get; set; }
  public string? TransactionJournalId_Caption { get; set; }
}